# Problem Set 1 - Data Acquisition and Text Normalization

Name: **Jessica Mae T. Lanuzo**                | Section: **BSCS 3A**
<hr>

### Dataset used: Spotify User Reviews

Description from Kaggle:
- This dataset consists of 51,000+ user reviews of the Spotify application from the Google Play Store (January - July 2022). The reviews have been scraped to analyze user sentiments and feedback towards the app. Each review has been labeled as either "Positive" or "Negative" based on its sentiment. The distribution of sentiments within the dataset is as follows:
Negative Reviews: 56% of the total reviews. - Positive Reviews: 44% of the total reviews

- This dataset can be used to perform various analyses such as sentiment analysis, trend analysis over time, and feature extraction to gain insights into user experience and satisfaction with the Spotify app. It serves as a valuable resource for researchers and developers who want to explore user perceptions and identify areas of improvement for the application.

Available at: https://www.kaggle.com/datasets/alexandrakim2201/spotify-dataset

# Implementation

### Setting up libraries

In [1]:
!pip3 install pandas nltk

Requirement already satisfied: pandas in c:\users\jessica\appdata\local\programs\python\python313\lib\site-packages (3.0.0)
Requirement already satisfied: nltk in c:\users\jessica\appdata\local\programs\python\python313\lib\site-packages (3.9.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jessica\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jessica\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\jessica\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: click in c:\users\jessica\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\jessica\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\jessica\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2026.1.15)
Requirement already satisfied: tqdm in c:\users\jessica\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: six>=1.5 in c:\users\jessica\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\jessica\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import nltk
import re
from nltk.corpus import brown
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jessica\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Jessica\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Jessica\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

### Importing dataset

In [3]:
pd.set_option('display.max_colwidth', None)

In [4]:
# Import dataset
df = pd.read_csv('DATASET.csv', encoding="utf-8")

# Preview first 5 instances
df.head()

,Review,label
0,"Great music service, the audio is high quality and the app is easy to use. Also very quick and friendly support.",POSITIVE
1,Please ignore previous negative rating. This app is super great. I give it five stars+,POSITIVE
2,"This pop-up ""Get the best Spotify experience on Android 12"" is too annoying. Please let's get rid of this.",NEGATIVE
3,Really buggy and terrible to use as of recently,NEGATIVE
4,Dear Spotify why do I get songs that I didn't put on my playlist??? And why do we have shuffle play?,NEGATIVE

#### The Dataset

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52702 entries, 0 to 52701
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  52686 non-null  str
 1   label   52702 non-null  str
dtypes: str(2)
memory usage: 823.6 KB

In [7]:
df = df.drop(columns=['label'])
# Preview first 5 instances
df.head()

                                                                                                             Review
0  Great music service, the audio is high quality and the app is easy to use. Also very quick and friendly support.
1                            Please ignore previous negative rating. This app is super great. I give it five stars+
2        This pop-up "Get the best Spotify experience on Android 12" is too annoying. Please let's get rid of this.
3                                                                   Really buggy and terrible to use as of recently
4              Dear Spotify why do I get songs that I didn't put on my playlist??? And why do we have shuffle play?

### Unitize and Tokenize

In [8]:
# Handle missing values, apply word_tokenize to each entry in 'Review' column
df['tokenized_review'] = df['Review'].fillna('').apply(word_tokenize)

# Preview first 5 instances
df.head()

,Review,tokenized_review
0,"Great music service, the audio is high quality and the app is easy to use. Also very quick and friendly support.","[Great, music, service, ,, the, audio, is, high, quality, and, the, app, is, easy, to, use, ., Also, very, quick, and, friendly, support, .]"
1,Please ignore previous negative rating. This app is super great. I give it five stars+,"[Please, ignore, previous, negative, rating, ., This, app, is, super, great, ., I, give, it, five, stars+]"
2,"This pop-up ""Get the best Spotify experience on Android 12"" is too annoying. Please let's get rid of this.","[This, pop-up, ``, Get, the, best, Spotify, experience, on, Android, 12, '', is, too, annoying, ., Please, let, 's, get, rid, of, this, .]"
3,Really buggy and terrible to use as of recently,"[Really, buggy, and, terrible, to, use, as, of, recently]"
4,Dear Spotify why do I get songs that I didn't put on my playlist??? And why do we have shuffle play?,"[Dear, Spotify, why, do, I, get, songs, that, I, did, n't, put, on, my, playlist, ?, ?, ?, And, why, do, we, have, shuffle, play, ?]"

### Lowercase

In [10]:
# Convert tokens to lowercase
df['tokenized_review'] = df['tokenized_review'].apply(lambda x: [token.lower() for token in x])

# Preview first 5 instances
df.head()

,Review,tokenized_review
0,"Great music service, the audio is high quality and the app is easy to use. Also very quick and friendly support.","[great, music, service, ,, the, audio, is, high, quality, and, the, app, is, easy, to, use, ., also, very, quick, and, friendly, support, .]"
1,Please ignore previous negative rating. This app is super great. I give it five stars+,"[please, ignore, previous, negative, rating, ., this, app, is, super, great, ., i, give, it, five, stars+]"
2,"This pop-up ""Get the best Spotify experience on Android 12"" is too annoying. Please let's get rid of this.","[this, pop-up, ``, get, the, best, spotify, experience, on, android, 12, '', is, too, annoying, ., please, let, 's, get, rid, of, this, .]"
3,Really buggy and terrible to use as of recently,"[really, buggy, and, terrible, to, use, as, of, recently]"
4,Dear Spotify why do I get songs that I didn't put on my playlist??? And why do we have shuffle play?,"[dear, spotify, why, do, i, get, songs, that, i, did, n't, put, on, my, playlist, ?, ?, ?, and, why, do, we, have, shuffle, play, ?]"

### Remove Tokens with Numbers

In [11]:
df['tokenized_review'] = df['tokenized_review'].apply(lambda x: [token.lower() for token in x if not any(char.isdigit() for char in token)])

# Preview first 5 instances
df.head()

,Review,tokenized_review
0,"Great music service, the audio is high quality and the app is easy to use. Also very quick and friendly support.","[great, music, service, ,, the, audio, is, high, quality, and, the, app, is, easy, to, use, ., also, very, quick, and, friendly, support, .]"
1,Please ignore previous negative rating. This app is super great. I give it five stars+,"[please, ignore, previous, negative, rating, ., this, app, is, super, great, ., i, give, it, five, stars+]"
2,"This pop-up ""Get the best Spotify experience on Android 12"" is too annoying. Please let's get rid of this.","[this, pop-up, ``, get, the, best, spotify, experience, on, android, '', is, too, annoying, ., please, let, 's, get, rid, of, this, .]"
3,Really buggy and terrible to use as of recently,"[really, buggy, and, terrible, to, use, as, of, recently]"
4,Dear Spotify why do I get songs that I didn't put on my playlist??? And why do we have shuffle play?,"[dear, spotify, why, do, i, get, songs, that, i, did, n't, put, on, my, playlist, ?, ?, ?, and, why, do, we, have, shuffle, play, ?]"

### Remove Special Characters and White Spaces

In [12]:
import re

# Remove special characters from tokens
df['tokenized_review'] = df['tokenized_review'].apply(
    lambda x: [token for token in 
               (re.sub(r'[^a-zA-Z0-9]', '', t) for t in x)
               if token]
)

# Preview first 5 instances
df.head()

,Review,tokenized_review
0,"Great music service, the audio is high quality and the app is easy to use. Also very quick and friendly support.","[great, music, service, the, audio, is, high, quality, and, the, app, is, easy, to, use, also, very, quick, and, friendly, support]"
1,Please ignore previous negative rating. This app is super great. I give it five stars+,"[please, ignore, previous, negative, rating, this, app, is, super, great, i, give, it, five, stars]"
2,"This pop-up ""Get the best Spotify experience on Android 12"" is too annoying. Please let's get rid of this.","[this, popup, get, the, best, spotify, experience, on, android, is, too, annoying, please, let, s, get, rid, of, this]"
3,Really buggy and terrible to use as of recently,"[really, buggy, and, terrible, to, use, as, of, recently]"
4,Dear Spotify why do I get songs that I didn't put on my playlist??? And why do we have shuffle play?,"[dear, spotify, why, do, i, get, songs, that, i, did, nt, put, on, my, playlist, and, why, do, we, have, shuffle, play]"

### Remove Stop Words

In [13]:
# Download and import english stopwords
stop_words = stopwords.words('english')
print(stop_words)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [14]:
# Remove stopwords from tokens
df['tokenized_review'] = df['tokenized_review'].apply(
    lambda x: [token for token in x if token.lower() not in stop_words]
)

# Preview first 5 instances
df.head()

,Review,tokenized_review
0,"Great music service, the audio is high quality and the app is easy to use. Also very quick and friendly support.","[great, music, service, audio, high, quality, app, easy, use, also, quick, friendly, support]"
1,Please ignore previous negative rating. This app is super great. I give it five stars+,"[please, ignore, previous, negative, rating, app, super, great, give, five, stars]"
2,"This pop-up ""Get the best Spotify experience on Android 12"" is too annoying. Please let's get rid of this.","[popup, get, best, spotify, experience, android, annoying, please, let, get, rid]"
3,Really buggy and terrible to use as of recently,"[really, buggy, terrible, use, recently]"
4,Dear Spotify why do I get songs that I didn't put on my playlist??? And why do we have shuffle play?,"[dear, spotify, get, songs, nt, put, playlist, shuffle, play]"

### Stemming

In [15]:
from nltk.stem import PorterStemmer

# Initialize the Porter Stemmer
stemmer = PorterStemmer()

# Apply stemming to tokens
df['stemmed_review'] = df['tokenized_review'].apply(lambda x: [stemmer.stem(token) for token in x])

# Preview first 5 instances
df.head()

,Review,tokenized_review,stemmed_review
0,"Great music service, the audio is high quality and the app is easy to use. Also very quick and friendly support.","[great, music, service, audio, high, quality, app, easy, use, also, quick, friendly, support]","[great, music, servic, audio, high, qualiti, app, easi, use, also, quick, friendli, support]"
1,Please ignore previous negative rating. This app is super great. I give it five stars+,"[please, ignore, previous, negative, rating, app, super, great, give, five, stars]","[pleas, ignor, previou, neg, rate, app, super, great, give, five, star]"
2,"This pop-up ""Get the best Spotify experience on Android 12"" is too annoying. Please let's get rid of this.","[popup, get, best, spotify, experience, android, annoying, please, let, get, rid]","[popup, get, best, spotifi, experi, android, annoy, pleas, let, get, rid]"
3,Really buggy and terrible to use as of recently,"[really, buggy, terrible, use, recently]","[realli, buggi, terribl, use, recent]"
4,Dear Spotify why do I get songs that I didn't put on my playlist??? And why do we have shuffle play?,"[dear, spotify, get, songs, nt, put, playlist, shuffle, play]","[dear, spotifi, get, song, nt, put, playlist, shuffl, play]"

### Lemmatization

In [16]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

# Initialize WordNet Lemmatizer
lemmatizer = WordNetLemmatizer()

# Apply lemmatization to each token
df['lemmatized_review'] = df['tokenized_review'].apply(lambda x: [lemmatizer.lemmatize(token) for token in x])

# Preview first 3 instances
df.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Jessica\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Jessica\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

,Review,tokenized_review,stemmed_review,lemmatized_review
0,"Great music service, the audio is high quality and the app is easy to use. Also very quick and friendly support.","[great, music, service, audio, high, quality, app, easy, use, also, quick, friendly, support]","[great, music, servic, audio, high, qualiti, app, easi, use, also, quick, friendli, support]","[great, music, service, audio, high, quality, app, easy, use, also, quick, friendly, support]"
1,Please ignore previous negative rating. This app is super great. I give it five stars+,"[please, ignore, previous, negative, rating, app, super, great, give, five, stars]","[pleas, ignor, previou, neg, rate, app, super, great, give, five, star]","[please, ignore, previous, negative, rating, app, super, great, give, five, star]"
2,"This pop-up ""Get the best Spotify experience on Android 12"" is too annoying. Please let's get rid of this.","[popup, get, best, spotify, experience, android, annoying, please, let, get, rid]","[popup, get, best, spotifi, experi, android, annoy, pleas, let, get, rid]","[popup, get, best, spotify, experience, android, annoying, please, let, get, rid]"
3,Really buggy and terrible to use as of recently,"[really, buggy, terrible, use, recently]","[realli, buggi, terribl, use, recent]","[really, buggy, terrible, use, recently]"
4,Dear Spotify why do I get songs that I didn't put on my playlist??? And why do we have shuffle play?,"[dear, spotify, get, songs, nt, put, playlist, shuffle, play]","[dear, spotifi, get, song, nt, put, playlist, shuffl, play]","[dear, spotify, get, song, nt, put, playlist, shuffle, play]"

# Results

In [17]:
df

,Review,tokenized_review,stemmed_review,lemmatized_review
0,"Great music service, the audio is high quality and the app is easy to use. Also very quick and friendly support.","[great, music, service, audio, high, quality, app, easy, use, also, quick, friendly, support]","[great, music, servic, audio, high, qualiti, app, easi, use, also, quick, friendli, support]","[great, music, service, audio, high, quality, app, easy, use, also, quick, friendly, support]"
1,Please ignore previous negative rating. This app is super great. I give it five stars+,"[please, ignore, previous, negative, rating, app, super, great, give, five, stars]","[pleas, ignor, previou, neg, rate, app, super, great, give, five, star]","[please, ignore, previous, negative, rating, app, super, great, give, five, star]"
2,"This pop-up ""Get the best Spotify experience on Android 12"" is too annoying. Please let's get rid of this.","[popup, get, best, spotify, experience, android, annoying, please, let, get, rid]","[popup, get, best, spotifi, experi, android, annoy, pleas, let, get, rid]","[popup, get, best, spotify, experience, android, annoying, please, let, get, rid]"
3,Really buggy and terrible to use as of recently,"[really, buggy, terrible, use, recently]","[realli, buggi, terribl, use, recent]","[really, buggy, terrible, use, recently]"
4,Dear Spotify why do I get songs that I didn't put on my playlist??? And why do we have shuffle play?,"[dear, spotify, get, songs, nt, put, playlist, shuffle, play]","[dear, spotifi, get, song, nt, put, playlist, shuffl, play]","[dear, spotify, get, song, nt, put, playlist, shuffle, play]"
...,...,...,...,...
52697,Yes the best,"[yes, best]","[ye, best]","[yes, best]"
52698,Spotify won my heart in Feb 2024 You won my heart With music and lyrics and then language educational podcasts and audio books you finally won my heart over With just a free trial and I was convinced I found what I have been looking for all these while and finally settling down with this like marriage haha,"[spotify, heart, feb, heart, music, lyrics, language, educational, podcasts, audio, books, finally, heart, free, trial, convinced, found, looking, finally, settling, like, marriage, haha]","[spotifi, heart, feb, heart, music, lyric, languag, educ, podcast, audio, book, final, heart, free, trial, convinc, found, look, final, settl, like, marriag, haha]","[spotify, heart, feb, heart, music, lyric, language, educational, podcasts, audio, book, finally, heart, free, trial, convinced, found, looking, finally, settling, like, marriage, haha]"
52699,I tried to open the app and it wont open I restarted my phone but Ill tap the icon itll freeze and then send me to my home screen I uninstalled and reinstalled and that fixed it for a day but now its happening again I dont want to have to redownload everything again,"[tried, open, app, wont, open, restarted, phone, ill, tap, icon, itll, freeze, send, home, screen, uninstalled, reinstalled, fixed, day, happening, dont, want, redownload, everything]","[tri, open, app, wont, open, restart, phone, ill, tap, icon, itll, freez, send, home, screen, uninstal, reinstal, fix, day, happen, dont, want, redownload, everyth]","[tried, open, app, wont, open, restarted, phone, ill, tap, icon, itll, freeze, send, home, screen, uninstalled, reinstalled, fixed, day, happening, dont, want, redownload, everything]"
52700,Good,[good],[good],[good]
52701,Nice app to play music and at very affordable price,"[nice, app, play, music, affordable, price]","[nice, app, play, music, afford, price]","[nice, app, play, music, affordable, price]"

In [18]:
df.iloc[13]

Review               i hav any music that i like it is superðŸ™Œ
tokenized_review                       [hav, music, like, super]
stemmed_review                         [hav, music, like, super]
lemmatized_review                      [hav, music, like, super]
Name: 13, dtype: object