# Problem Set 2 - N-Gram Model Construction

Name: **Jessica Mae T. Lanuzo**                | Section: **BSCS 3A**
<hr>

### Dataset used: House MD Transcripts (Season 1)

Description from Kaggle:
- House M.D is an American television medical drama that originally ran on the Fox network for eight seasons, from November 16, 2004 to May 21, 2012. The show's main character is Dr. Gregory House, a pain medication-dependent, unconventional, misanthropic medical genius who leads a team of diagnostic fellows at the fictional Princeton–Plainsboro Teaching Hospital (PPTH) in Princeton, New Jersey.

Available at: https://www.kaggle.com/datasets/kunalbhar/house-md-transcripts/data

# Implementation

## I. Preprocessing

### Setting up libraries

In [1]:
!pip3 install pandas nltk

In [2]:
import pandas as pd
import nltk
import re
nltk.download('punkt')
from nltk.tokenize import sent_tokenize
from itertools import chain

from collections import Counter

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Jessica\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

### Importing the dataset

In [3]:
pd.set_option('display.max_colwidth', None)

In [4]:
# Import dataset
df = pd.read_csv('season1.csv', encoding="latin1")

# Preview first 5 instances
df

,name,line
0,Melanie,Why are you late?
1,Rebecca,You're not going to like the answer.
2,Melanie,I already know the answer.
3,Rebecca,I missed the bus.
4,Melanie,"I don't doubt it, no bus stops near Brad's. You spent the night, the alarm didn't work. Or maybe it did."
...,...,...
9791,House,"[loudly] I will not have sex with you! Not again! Miserable, that first time. All that desperate, administrative need """
9792,Cuddy,"Stacy's husband is going to need close monitoring at the hospital. And since we can definitely use her back here, I've offered her a job. General Counsel."
9793,House,Did she say yes?
9794,Cuddy,"She said only if it was okay with you. [House starts to walk off as The Rolling Stones' ""You Can't Always Get What You Want"" plays ironically in the background.] Yes or no?"
9795,House,Fine. Good.

### Preparing Dataset

#### Removing bracketed stage directions

In [5]:
# Remove stage directions (text within brackets)
df['line'] = df['line'].apply(
    lambda x: re.sub(r'\[.*?\]', '', str(x))
    )

df

,name,line
0,Melanie,Why are you late?
1,Rebecca,You're not going to like the answer.
2,Melanie,I already know the answer.
3,Rebecca,I missed the bus.
4,Melanie,"I don't doubt it, no bus stops near Brad's. You spent the night, the alarm didn't work. Or maybe it did."
...,...,...
9791,House,"I will not have sex with you! Not again! Miserable, that first time. All that desperate, administrative need """
9792,Cuddy,"Stacy's husband is going to need close monitoring at the hospital. And since we can definitely use her back here, I've offered her a job. General Counsel."
9793,House,Did she say yes?
9794,Cuddy,She said only if it was okay with you. Yes or no?
9795,House,Fine. Good.

#### Removing "name" column

In [6]:
df = df.drop(columns=['name'])
# Preview first 5 instances
df.head()

                                                                                                        line
0                                                                                          Why are you late?
1                                                                       You're not going to like the answer.
2                                                                                 I already know the answer.
3                                                                                          I missed the bus.
4   I don't doubt it, no bus stops near Brad's. You spent the night, the alarm didn't work. Or maybe it did.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9796 entries, 0 to 9795
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   line    9796 non-null   object
dtypes: object(1)
memory usage: 76.7+ KB

In [8]:
num_docs = len(df)
total_words = df['line'].apply(lambda x: len(str(x).split())).sum()

print("Number of documents:", num_docs)
print("Total words:", total_words)

Number of documents: 9796
Total words: 108234

### Text Normalization

In [9]:
# Convert text to lowercase
df['normalized'] = df['line'].apply(lambda x: str(x).lower())

# Preview first 5 instances
df.head()

,line,normalized
0,Why are you late?,why are you late?
1,You're not going to like the answer.,you're not going to like the answer.
2,I already know the answer.,i already know the answer.
3,I missed the bus.,i missed the bus.
4,"I don't doubt it, no bus stops near Brad's. You spent the night, the alarm didn't work. Or maybe it did.","i don't doubt it, no bus stops near brad's. you spent the night, the alarm didn't work. or maybe it did."

### Sentence Tokenization

In [10]:
df['sentences'] = df['normalized'].apply(sent_tokenize)

# Preview first 5 instances
df.head()

,line,normalized,sentences
0,Why are you late?,why are you late?,[ why are you late?]
1,You're not going to like the answer.,you're not going to like the answer.,[ you're not going to like the answer.]
2,I already know the answer.,i already know the answer.,[ i already know the answer.]
3,I missed the bus.,i missed the bus.,[ i missed the bus.]
4,"I don't doubt it, no bus stops near Brad's. You spent the night, the alarm didn't work. Or maybe it did.","i don't doubt it, no bus stops near brad's. you spent the night, the alarm didn't work. or maybe it did.","[ i don't doubt it, no bus stops near brad's., you spent the night, the alarm didn't work., or maybe it did.]"

### Removal of punctuation and special characters

In [11]:
def clean_sentence(sentence):
    sentence = re.sub(r"[^a-z0-9\s]", "", sentence)  # remove punctuation
    sentence = re.sub(r"\s+", " ", sentence).strip() # remove extra spaces
    return sentence

df['clean_sentences'] = df['sentences'].apply(
    lambda s_list: [clean_sentence(s) for s in s_list]
)

# Preview first 5 instances
df.head()

,line,normalized,sentences,clean_sentences
0,Why are you late?,why are you late?,[ why are you late?],[why are you late]
1,You're not going to like the answer.,you're not going to like the answer.,[ you're not going to like the answer.],[youre not going to like the answer]
2,I already know the answer.,i already know the answer.,[ i already know the answer.],[i already know the answer]
3,I missed the bus.,i missed the bus.,[ i missed the bus.],[i missed the bus]
4,"I don't doubt it, no bus stops near Brad's. You spent the night, the alarm didn't work. Or maybe it did.","i don't doubt it, no bus stops near brad's. you spent the night, the alarm didn't work. or maybe it did.","[ i don't doubt it, no bus stops near brad's., you spent the night, the alarm didn't work., or maybe it did.]","[i dont doubt it no bus stops near brads, you spent the night the alarm didnt work, or maybe it did]"

### Addition of Sentence Boundary Tokens

In [12]:
def add_boundaries(sent_list):
    return [f"<s> {s} </s>" for s in sent_list]

df['bounded_sentences'] = df['clean_sentences'].apply(add_boundaries)

# Preview first 5 instances
df.head()

,line,normalized,sentences,clean_sentences,bounded_sentences
0,Why are you late?,why are you late?,[ why are you late?],[why are you late],[<s> why are you late </s>]
1,You're not going to like the answer.,you're not going to like the answer.,[ you're not going to like the answer.],[youre not going to like the answer],[<s> youre not going to like the answer </s>]
2,I already know the answer.,i already know the answer.,[ i already know the answer.],[i already know the answer],[<s> i already know the answer </s>]
3,I missed the bus.,i missed the bus.,[ i missed the bus.],[i missed the bus],[<s> i missed the bus </s>]
4,"I don't doubt it, no bus stops near Brad's. You spent the night, the alarm didn't work. Or maybe it did.","i don't doubt it, no bus stops near brad's. you spent the night, the alarm didn't work. or maybe it did.","[ i don't doubt it, no bus stops near brad's., you spent the night, the alarm didn't work., or maybe it did.]","[i dont doubt it no bus stops near brads, you spent the night the alarm didnt work, or maybe it did]","[<s> i dont doubt it no bus stops near brads </s>, <s> you spent the night the alarm didnt work </s>, <s> or maybe it did </s>]"

### Tokenization into Word Lists

In [13]:
df['tokenized'] = df['bounded_sentences'].apply(
    lambda s_list: [sentence.split() for sentence in s_list]
)
# Preview first 5 instances
df.head()

,line,normalized,sentences,clean_sentences,bounded_sentences,tokenized
0,Why are you late?,why are you late?,[ why are you late?],[why are you late],[<s> why are you late </s>],"[[<s>, why, are, you, late, </s>]]"
1,You're not going to like the answer.,you're not going to like the answer.,[ you're not going to like the answer.],[youre not going to like the answer],[<s> youre not going to like the answer </s>],"[[<s>, youre, not, going, to, like, the, answer, </s>]]"
2,I already know the answer.,i already know the answer.,[ i already know the answer.],[i already know the answer],[<s> i already know the answer </s>],"[[<s>, i, already, know, the, answer, </s>]]"
3,I missed the bus.,i missed the bus.,[ i missed the bus.],[i missed the bus],[<s> i missed the bus </s>],"[[<s>, i, missed, the, bus, </s>]]"
4,"I don't doubt it, no bus stops near Brad's. You spent the night, the alarm didn't work. Or maybe it did.","i don't doubt it, no bus stops near brad's. you spent the night, the alarm didn't work. or maybe it did.","[ i don't doubt it, no bus stops near brad's., you spent the night, the alarm didn't work., or maybe it did.]","[i dont doubt it no bus stops near brads, you spent the night the alarm didnt work, or maybe it did]","[<s> i dont doubt it no bus stops near brads </s>, <s> you spent the night the alarm didnt work </s>, <s> or maybe it did </s>]","[[<s>, i, dont, doubt, it, no, bus, stops, near, brads, </s>], [<s>, you, spent, the, night, the, alarm, didnt, work, </s>], [<s>, or, maybe, it, did, </s>]]"

### Flatten tokens into training corpus

In [14]:
corpus = list(chain.from_iterable(
    chain.from_iterable(df['tokenized'])
))

corpus

['<s>',
 'why',
 'are',
 'you',
 'late',
 '</s>',
 '<s>',
 'youre',
 'not',
 'going',
 'to',
 'like',
 'the',
 'answer',
 '</s>',
 '<s>',
 'i',
 'already',
 'know',
 'the',
 'answer',
 '</s>',
 '<s>',
 'i',
 'missed',
 'the',
 'bus',
 '</s>',
 '<s>',
 'i',
 'dont',
 'doubt',
 'it',
 'no',
 'bus',
 'stops',
 'near',
 'brads',
 '</s>',
 '<s>',
 'you',
 'spent',
 'the',
 'night',
 'the',
 'alarm',
 'didnt',
 'work',
 '</s>',
 '<s>',
 'or',
 'maybe',
 'it',
 'did',
 '</s>',
 '<s>',
 'i',
 'didnt',
 'sleep',
 'with',
 'him',
 '</s>',
 '<s>',
 'girl',
 'theres',
 '</s>',
 '<s>',
 'i',
 'missed',
 'the',
 'bus',
 '</s>',
 '<s>',
 'theres',
 'something',
 'either',
 'very',
 'wrong',
 'with',
 'you',
 'or',
 'theres',
 'something',
 'very',
 'wrong',
 'with',
 'him',
 '</s>',
 '<s>',
 'theres',
 'nothing',
 'wrong',
 'with',
 'him',
 '</s>',
 '<s>',
 'please',
 'tell',
 'me',
 'you',
 'know',
 'that',
 'for',
 'a',
 'fact',
 '</s>',
 '<s>',
 'melanie',
 'i',
 'gotta',
 'go',
 '</s>',
 '<s>',
 'youre',
 'lying',
 'arent',
 'you',
 '</s>',
 '<s>',
 'i',
 'wouldnt',
 'lie',
 'to',
 'you',
 '</s>',
 '<s>',
 'good',
 'morning',
 'guys',
 '</s>',
 '<s>',
 'good',
 'morning',
 'miss',
 'rebecca',
 '</s>',
 '<s>',
 'everybodys',
 'in',
 'their',
 'seats',
 '</s>',
 '<s>',
 'yes',
 '</s>',
 '<s>',
 'ok',
 'sidney',
 'why',
 'dont',
 'you',
 'tell',
 'us',
 'what',
 'you',
 'did',
 'this',
 'weekend',
 '</s>',
 '<s>',
 'come',
 'on',
 'sidney',
 'we',
 'know',
 'youre',
 'not',
 'shy',
 '</s>',
 '<s>',
 'how',
 'come',
 'we',
 'always',
 'have',
 'to',
 'tell',
 'you',
 'what',
 'we',
 'did',
 'and',
 'you',
 'never',
 'tell',
 'us',
 'what',
 'you',
 'did',
 '</s>',
 '<s>',
 'ok',
 'i',
 'had',
 'a',
 'really',
 'great',
 'weekend',
 'but',
 'you',
 'cant',
 'tell',
 'miss',
 'melanie',
 'ok',
 '</s>',
 '<s>',
 'what',
 'did',
 'you',
 'do',
 '</s>',
 '<s>',
 'i',
 'made',
 'a',
 'new',
 'friend',
 '</s>',
 '<s>',
 'its',
 'so',
 'much',
 'fun',
 'to',
 'make',
 'new',
 'friends',
 'isnt',
 'it',
 '</s>',
 '<s>',
 'yeah',
 'yes',
 'etc',
 '</s>',
 '<s>',
 'absolutely',
 '</s>',
 '<s>',
 'you',
 'should',
 'never',
 'keep',
 'anything',
 'from',
 'your',
 'parents',
 '</s>',
 '<s>',
 'and',
 'i',
 'told',
 'them',
 '</s>',
 '<s>',
 'wh',
 '</s>',
 '<s>',
 'c',
 'a',
 't',
 'h',
 '</s>',
 '<s>',
 'the',
 '</s>',
 '<s>',
 'we',
 'know',
 'that',
 'word',
 'the',
 '</s>',
 '<s>',
 '29',
 'year',
 'old',
 'female',
 'first',
 'seizure',
 'one',
 'month',
 'ago',
 'lost',
 'the',
 'ability',
 'to',
 'speak',
 '</s>',
 '<s>',
 'babbled',
 'like',
 'a',
 'baby',
 '</s>',
 '<s>',
 'present',
 'deterioration',
 'of',
 'mental',
 'status',
 '</s>',
 '<s>',
 'see',
 'that',
 '</s>',
 '<s>',
 'they',
 'all',
 'assume',
 'im',
 'a',
 'patient',
 'because',
 'of',
 'this',
 'cane',
 '</s>',
 '<s>',
 'so',
 'put',
 'on',
 'a',
 'white',
 'coat',
 'like',
 'the',
 'rest',
 'of',
 'us',
 '</s>',
 '<s>',
 'i',
 'dont',
 'want',
 'them',
 'to',
 'think',
 'im',
 'a',
 'doctor',
 '</s>',
 '<s>',
 'you',
 'see',
 'where',
 'the',
 'administration',
 'might',
 'have',
 'a',
 'problem',
 'with',
 'that',
 'attitude',
 '</s>',
 '<s>',
 'people',
 'dont',
 'want',
 'a',
 'sick',
 'doctor',
 '</s>',
 '<s>',
 'fair',
 'enough',
 '</s>',
 '<s>',
 'i',
 'dont',
 'like',
 'healthy',
 'patients',
 '</s>',
 '<s>',
 'the',
 '29',
 'year',
 'old',
 'female',
 '</s>',
 '<s>',
 'the',
 'one',
 'who',
 'cant',
 'talk',
 'i',
 'liked',
 'that',
 'part',
 '</s>',
 '<s>',
 'shes',
 'my',
 'cousin',
 '</s>',
 '<s>',
 'and',
 'your',
 'cousin',
 'doesnt',
 'like',
 'the',
 'diagnosis',
 '</s>',
 '<s>',
 'i',
 'wouldnt',
 'either',
 '</s>',
 '<s>',
 'brain',
 'tumor',
 'shes',
 'gonna',
 'die',
 'boring',
 '</s>',
 '<s>',
 'no',
 'wonder',
 'youre',
 'such',
 'a',
 'renowned',
 'diagnostician',
 '</s>',
 '<s>',
 'you',
 'dont',
 'need',
 'to',
 'actually',
 'know',
 'anything',
 'to',
 'figure',
 'out',
 'whats',
 'wrong',
 '</s>',
 '<s>',
 'youre',
 'the',
 'oncologist',
 'im',
 'just',
 'a',
 'lowly',
 'infectious',
 'disease',
 'guy',
 '</s>',
 '<s>',
 'hah',
 'yes',
 'just',
 'a',
 'simple',
 'country',
 'doctor',
 '</s>',
 '<s>',
 'brain',
 'tumors',
 'at',
 'her',
 'age',
 'are',
 'highly',
 'unlikely',
 '</s>',
 '<s>',
 'shes',
 '29',
 'whatever',
 'shes',
 'got',
 'is',
 'highly',
 'unlikely',
 '</s>',
 '<s>',
 'protein',
 'markers',
 'for',
 'the',
 'three',
 'most',
 'prevalent',
 'brain',
 'cancers',
 'came',
 'up',
 'negative',
 '</s>',
 '<s>',
 'thats',
 'an',
 'hmo',
 'lab',
 'you',
 'might',
 'as',
 'well',
 'have',
 'sent',
 'it',
 'to',
 'a',
 'high',
 'school',
 'kid',
 'with',
 'a',
 'chemistry',
 'set',
 '</s>',
 '<s>',
 'no',
 'family',
 'history',
 '</s>',
 '<s>',
 'i',
 'thought',
 'your',
 'uncle',
 'died',
 'of',
 'cancer',
 '</s>',
 '<s>',
 'other',
 'side',
 '</s>',
 '<s>',
 'no',
 'environmental',
 'factors',
 '</s>',
 '<s>',
 'that',
 'you',
 'know',
 'of',
 '</s>',
 '<s>',
 'and',
 'shes',
 'not',
 'responding',
 'to',
 'radiation',
 'treatment',
 '</s>',
 '<s>',
 'none',
 'of',
 'which',
 'is',
 'even',
 'close',
 'to',
 'dispositive',
 '</s>',
 '<s>',
 'all',
 'it',
 'does',
 'is',
 'raise',
 'one',
 'question',
 '</s>',
 '<s>',
 'your',
 'cousin',
 'goes',
 'to',
 'an',
 'hmo',
 '</s>',
 '<s>',
 'come',
 'on',
 '</s>',
 '<s>',
 'why',
 'leave',
 'all',
 'the',
 'fun',
 'for',
 'the',
 'coroner',
 '</s>',
 '<s>',
 'whats',
 'the',
 'point',
 'of',
 'putting',
 'together',
 'a',
 'team',
 'if',
 'youre',
 'not',
 'going',
 'to',
 'use',
 'them',
 '</s>',
 '<s>',
 'youve',
 'got',
 'three',
 'overqualified',
 'doctors',
 'working',
 'for',
 'you',
 '</s>',
 '<s>',
 'getting',
 'bored',
 '</s>',
 '<s>',
 'its',
 'a',
 'lesion',
 '</s>',
 '<s>',
 'and',
 'the',
 'big',
 'green',
 'thing',
 'in',
 'the',
 'middle',
 'of',
 'the',
 'bigger',
 'blue',
 'thing',
 'on',
 'a',
 'map',
 'is',
 'an',
 'island',
 '</s>',
 '<s>',
 'i',
 'was',
 'hoping',
 'for',
 'something',
 'a',
 'bit',
 'more',
 'creative',
 '</s>',
 '<s>',
 'shouldnt',
 'we',
 'be',
 'speaking',
 'to',
 'the',
 'patient',
 'before',
 'we',
 'start',
 'diagnosing',
 '</s>',
 '<s>',
 'is',
 'she',
 'a',
 'doctor',
 '</s>',
 '<s>',
 'no',
 'but',
 '</s>',
 '<s>',
 'everybody',
 'lies',
 '</s>',
 '<s>',
 'dr',
 'house',
 'doesnt',
 'like',
 'dealing',
 'with',
 'patients',
 '</s>',
 '<s>',
 'isnt',
 'treating',
 'patients',
 'why',
 'we',
 'became',
 'doctors',
 '</s>',
 '<s>',
 'no',
 'treating',
 'illnesses',
 'is',
 'why',
 'we',
 'became',
 'doctors',
 'treating',
 'patients',
 'is',
 'what',
 'makes',
 'most',
 'doctors',
 'miserable',
 '</s>',
 '<s>',
 'so',
 'youre',
 'trying',
 'to',
 'eliminate',
 'the',
 'humanity',
 'from',
 'the',
 'practice',
 'of',
 'medicine',
 '</s>',
 '<s>',
 'if',
 'we',
 'dont',
 'talk',
 'to',
 'them',
 'they',
 'cant',
 'lie',
 'to',
 'us',
 'and',
 'we',
 'cant',
 'lie',
 'to',
 'them',
 '</s>',
 '<s>',
 'humanity',
 'is',
 'overrated',
 '</s>',
 '<s>',
 'i',
 'dont',
 'think',
 'its',
 'a',
 'tumor',
 '</s>',
 '<s>',
 'first',
 'year',
 'of',
 'medical',
 'school',
 'if',
 'you',
 'hear',
 'hoof',
 'beats',
 'you',
 'think',
 'horses',
 'not',
 'zebras',
 '</s>',
 '<s>',
 'are',
 'you',
 'in',
 'first',
 'year',
 'of',
 'medical',
 'school',
 '</s>',
 '<s>',
 'no',
 '</s>',
 '<s>',
 'first',
 'of',
 'all',
 'theres',
 'nothing',
 'on',
 'the',
 'cat',
 'scan',
 '</s>',
 '<s>',
 'second',
 'of',
 'all',
 'if',
 'this',
 'is',
 'a',
 'horse',
 'then',
 'the',
 'kindly',
 'family',
 'doctor',
 'in',
 'trenton',
 'makes',
 'the',
 'obvious',
 'diagnosis',
 'and',
 'it',
 'never',
 'gets',
 'near',
 'this',
 'office',
 '</s>',
 '<s>',
 'differential',
 'diagnosis',
 'people',
 'if',
 'its',
 'not',
 'a',
 'tumor',
 'what',
 'are',
 'the',
 'suspects',
 '</s>',
 '<s>',
 'why',
 'couldnt',
 'she',
 'talk',
 '</s>',
 '<s>',
 'aneurysm',
 'stroke',
 'or',
 'some',
 'other',
 'ischemic',
 'syndrome',
 '</s>',
 '<s>',
 'get',
 'her',
 'a',
 'contrast',
 'mri',
 '</s>',
 '<s>',
 'creutzfeldjakob',
 'disease',
 '</s>',
 '<s>',
 'mad',
 'cow',
 '</s>',
 '<s>',
 'mad',
 'zebra',
 '</s>',
 '<s>',
 'wernickies',
 'encephalopathy',
 '</s>',
 '<s>',
 'no',
 'blood',
 'thiamine',
 'level',
 'was',
 'normal',
 '</s>',
 '<s>',
 'lab',
 'in',
 'trenton',
 'could',
 'have',
 'screwed',
 'up',
 'the',
 'blood',
 'test',
 '</s>',
 '<s>',
 'i',
 'assume',
 'its',
 'a',
 'corollary',
 'if',
 'people',
 'lie',
 'that',
 'people',
 'screw',
 'up',
 '</s>',
 '<s>',
 'redraw',
 'the',
 'blood',
 'tests',
 '</s>',
 '<s>',
 'and',
 'get',
 'her',
 'scheduled',
 'for',
 'that',
 'contrast',
 'mri',
 'asap',
 '</s>',
 '<s>',
 'lets',
 'find',
 'out',
 'what',
 'kind',
 'of',
 'zebra',
 'were',
 'dealing',
 'with',
 'here',
 '</s>',
 '<s>',
 'i',
 'was',
 'expecting',
 'you',
 'in',
 'my',
 'office',
 '20',
 'minutes',
 'ago',
 '</s>',
 '<s>',
 'really',
 '</s>',
 '<s>',
 'well',
 'thats',
 'odd',
 'because',
 'i',
 'had',
 'no',
 'intention',
 'of',
 'being',
 'in',
 'your',
 'office',
 '20',
 'minutes',
 'ago',
 '</s>',
 '<s>',
 'you',
 'think',
 'we',
 'have',
 ...]

## II. N-Gram Modeling

### Unigram Model

In [15]:
def build_ngrams(tokens, n):
    return [tuple(tokens[i:i+n]) for i in range(len(tokens)-n+1)]

# Build model
unigrams = build_ngrams(corpus, 1)

In [16]:
# Frequency count
unigram_counts = Counter(unigrams)

unigram_counts

Counter({('<s>',): 16509,
         ('</s>',): 16509,
         ('the',): 3727,
         ('you',): 3426,
         ('to',): 2571,
         ('a',): 2558,
         ('i',): 2346,
         ('it',): 1409,
         ('and',): 1399,
         ('of',): 1223,
         ('is',): 1064,
         ('that',): 1051,
         ('in',): 998,
         ('its',): 941,
         ('not',): 918,
         ('no',): 871,
         ('what',): 854,
         ('your',): 842,
         ('for',): 803,
         ('have',): 763,
         ('we',): 746,
         ('he',): 726,
         ('do',): 703,
         ('on',): 699,
         ('this',): 693,
         ('be',): 675,
         ('im',): 660,
         ('me',): 649,
         ('her',): 646,
         ('if',): 627,
         ('was',): 590,
         ('dont',): 566,
         ('with',): 553,
         ('him',): 550,
         ('youre',): 537,
         ('just',): 535,
         ('but',): 525,
         ('know',): 523,
         ('my',): 522,
         ('so',): 490,
         ('get',): 489,
         ('are',): 487,
         ('his',): 483,
         ('she',): 475,
         ('right',): 429,
         ('well',): 428,
         ('were',): 411,
         ('about',): 409,
         ('can',): 403,
         ('hes',): 402,
         ('all',): 396,
         ('thats',): 380,
         ('one',): 373,
         ('out',): 373,
         ('got',): 369,
         ('up',): 369,
         ('like',): 367,
         ('an',): 360,
         ('think',): 357,
         ('they',): 348,
         ('want',): 308,
         ('why',): 304,
         ('yeah',): 289,
         ('going',): 286,
         ('or',): 285,
         ('how',): 274,
         ('shes',): 274,
         ('could',): 272,
         ('at',): 270,
         ('cant',): 260,
         ('need',): 256,
         ('would',): 255,
         ('did',): 243,
         ('because',): 243,
         ('gonna',): 238,
         ('here',): 237,
         ('as',): 235,
         ('there',): 234,
         ('house',): 232,
         ('go',): 231,
         ('oh',): 231,
         ('good',): 227,
         ('dr',): 227,
         ('from',): 224,
         ('theres',): 219,
         ('had',): 219,
         ('some',): 214,
         ('now',): 210,
         ('didnt',): 206,
         ('two',): 202,
         ('doesnt',): 199,
         ('okay',): 199,
         ('been',): 195,
         ('when',): 194,
         ('should',): 192,
         ('see',): 190,
         ('more',): 185,
         ('take',): 185,
         ('blood',): 184,
         ('back',): 183,
         ('then',): 182,
         ('time',): 182,
         ('wrong',): 179,
         ('has',): 175,
         ('them',): 174,
         ('whats',): 174,
         ('any',): 174,
         ('make',): 173,
         ('who',): 169,
         ('tell',): 164,
         ('something',): 162,
         ('sure',): 160,
         ('us',): 159,
         ('too',): 156,
         ('way',): 155,
         ('come',): 154,
         ('only',): 154,
         ('by',): 152,
         ('will',): 152,
         ('really',): 151,
         ('people',): 151,
         ('maybe',): 148,
         ('better',): 146,
         ('give',): 145,
         ('off',): 145,
         ('which',): 144,
         ('little',): 140,
         ('nothing',): 139,
         ('doing',): 138,
         ('said',): 137,
         ('never',): 131,
         ('does',): 131,
         ('other',): 130,
         ('say',): 130,
         ('look',): 127,
         ('sorry',): 126,
         ('ill',): 126,
         ('patient',): 124,
         ('cause',): 124,
         ('into',): 122,
         ('theyre',): 118,
         ('thing',): 117,
         ('even',): 116,
         ('still',): 116,
         ('brain',): 115,
         ('anything',): 114,
         ('much',): 113,
         ('guy',): 113,
         ('ive',): 113,
         ('down',): 113,
         ('than',): 109,
         ('very',): 108,
         ('bad',): 107,
         ('pain',): 106,
         ('yes',): 104,
         ('doctor',): 104,
         ('die',): 103,
         ('youve',): 103,
         ('hey',): 103,
         ('find',): 101,
         ('talk',): 100,
         ('treatment',): 100,
         ('their',): 99,
         ('might',): 99,
         ('heart',): 99,
         ('work',): 98,
         ('sick',): 97,
         ('call',): 97,
         ('three',): 93,
         ('getting',): 93,
         ('before',): 93,
         ('our',): 93,
         ('fine',): 93,
         ('cancer',): 92,
         ('start',): 92,
         ('new',): 90,
         ('old',): 90,
         ('let',): 89,
         ('test',): 88,
         ('am',): 88,
         ('god',): 88,
         ('first',): 87,
         ('patients',): 87,
         ('always',): 85,
         ('problem',): 85,
         ('kid',): 85,
         ('told',): 84,
         ('put',): 84,
         ('years',): 84,
         ('over',): 84,
         ('care',): 83,
         ('guys',): 82,
         ('big',): 82,
         ('hospital',): 82,
         ('long',): 81,
         ('being',): 80,
         ('mean',): 80,
         ('these',): 80,
         ('thought',): 78,
         ('chase',): 78,
         ('another',): 78,
         ('kids',): 78,
         ('symptoms',): 78,
         ('hell',): 78,
         ('great',): 77,
         ('where',): 77,
         ('last',): 77,
         ('everything',): 77,
         ('actually',): 75,
         ('else',): 75,
         ('isnt',): 74,
         ('keep',): 74,
         ('tests',): 74,
         ('again',): 74,
         ('uh',): 74,
         ('enough',): 73,
         ('wont',): 73,
         ('someone',): 73,
         ('wouldnt',): 72,
         ('id',): 72,
         ('probably',): 72,
         ('stop',): 71,
         ('home',): 71,
         ('pretty',): 71,
         ('love',): 71,
         ('lets',): 70,
         ('life',): 70,
         ('foreman',): 70,
         ('case',): 69,
         ('means',): 69,
         ('job',): 68,
         ('help',): 68,
         ('believe',): 68,
         ('surgery',): 68,
         ('made',): 67,
         ('doctors',): 67,
         ('nice',): 67,
         ('room',): 66,
         ('things',): 66,
         ('through',): 66,
         ('same',): 66,
         ('lie',): 65,
         ('tumor',): 65,
         ('looking',): 65,
         ('thank',): 65,
         ('talking',): 65,
         ('either',): 64,
         ('weve',): 64,
         ('baby',): 63,
         ('lot',): 63,
         ('drugs',): 63,
         ('mri',): 62,
         ('leg',): 62,
         ('cuddy',): 62,
         ('gotta',): 61,
         ('makes',): 61,
         ('also',): 61,
         ('hours',): 61,
         ('wait',): 61,
         ('feel',): 60,
         ('those',): 60,
         ('having',): 60,
         ('check',): 60,
         ('day',): 59,
         ('history',): 58,
         ('reason',): 58,
         ('point',): 57,
         ('medical',): 57,
         ('kind',): 57,
         ('next',): 57,
         ('gave',): 57,
         ('every',): 57,
         ('parents',): 56,
         ('hurt',): 56,
         ('course',): 56,
         ('mom',): 56,
         ('disease',): 55,
         ('away',): 55,
         ('pills',): 55,
         ('kill',): 55,
         ('please',): 54,
         ('treat',): 54,
         ('money',): 54,
         ('ok',): 53,
         ('guess',): 53,
         ('man',): 53,
         ('diagnosis',): 52,
         ('real',): 52,
         ('arent',): 51,
         ('cameron',): 51,
         ('wasnt',): 51,
         ('done',): 51,
         ('idea',): 51,
         ('took',): 51,
         ('infection',): 51,
         ('most',): 50,
         ('both',): 50,
         ('already',): 49,
         ('night',): 49,
         ('year',): 49,
         ('ago',): 49,
         ('week',): 49,
         ('dead',): 49,
         ('havent',): 49,
         ('son',): 49,
         ('liver',): 49,
         ('medicine',): 48,
         ('scan',): 48,
         ('dying',): 48,
         ('after',): 48,
         ('dad',): 48,
         ('rash',): 48,
         ('around',): 47,
         ('run',): 47,
         ('youll',): 47,
         ('sex',): 47,
         ('without',): 46,
         ('youd',): 46,
         ('few',): 45,
         ('must',): 45,
         ('found',): 45,
         ('live',): 45,
         ('wants',): 45,
         ('almost',): 45,
         ('figure',): 44,
         ('question',): 44,
         ('trying',): 44,
         ('while',): 44,
         ('use',): 43,
         ('sign',): 43,
         ('happened',): 43,
         ('stuff',): 43,
         ('called',): 43,
         ('negative',): 42,
         ('working',): 42,
         ('head',): 42,
         ('itll',): 42,
         ('wife',): 42,
         ('husband',): 42,
         ('days',): 42,
         ('ask',): 42,
         ('went',): 42,
         ('exactly',): 42,
         ('morning',): 41,
         ('gets',): 41,
         ('try',): 41,
         ('five',): 41,
         ('months',): 40,
         ('hold',): 40,
         ('since',): 40,
         ('system',): 40,
         ('unless',): 40,
         ('clean',): 40,
         ('fire',): 39,
         ('looks',): 39,
         ('steroids',): 39,
         ('huh',): 39,
         ('fever',): 39,
         ('saying',): 39,
         ('wanted',): 39,
         ('hand',): 39,
         ('leave',): 38,
         ('normal',): 38,
         ('hour',): 38,
         ('name',): 38,
         ('left',): 38,
         ('family',): 37,
         ('clinic',): 37,
         ('four',): 37,
         ('until',): 37,
         ('says',): 37,
         ('thinking',): 37,
         ('hi',): 37,
         ('came',): 36,
         ('school',): 36,
         ('trust',): 36,
         ('yourself',): 36,
         ('worry',): 36,
         ('taking',): 36,
         ('own',): 36,
         ('change',): 36,
         ('worse',): 36,
         ('control',): 36,
         ('show',): 36,
         ('save',): 36,
         ('needs',): 36,
         ('chance',): 36,
         ('antibiotics',): 36,
         ('kidney',): 36,
         ('car',): 36,
         ('arm',): 36,
         ('clot',): 36,
         ('vogler',): 36,
         ('high',): 35,
         ('second',): 35,
         ('minutes',): 35,
         ('least',): 35,
         ('ever',): 35,
         ('problems',): 35,
         ('making',): 35,
         ('knows',): 35,
         ('caused',): 35,
         ('person',): 35,
         ('news',): 35,
         ('whos',): 35,
         ('asked',): 35,
         ('ten',): 34,
         ('biopsy',): 34,
         ('many',): 34,
         ('woman',): 34,
         ('whoa',): 34,
         ('hard',): 34,
         ('mr',): 34,
         ('matter',): 34,
         ('best',): 34,
         ('likely',): 34,
         ('six',): 34,
         ('yet',): 34,
         ('rest',): 33,
         ('lab',): 33,
         ('ah',): 33,
         ('couple',): 33,
         ('used',): 33,
         ('body',): 33,
         ('whatever',): 32,
         ('weeks',): 32,
         ('may',): 32,
         ('allergic',): 32,
         ('happens',): 32,
         ('different',): 32,
         ('condition',): 32,
         ('lying',): 31,
         ('part',): 31,
         ('couldnt',): 31,
         ('screwed',): 31,
         ('once',): 31,
         ('whole',): 31,
         ('easy',): 31,
         ('mistake',): 31,
         ('damage',): 31,
         ('obviously',): 31,
         ('ones',): 31,
         ('remember',): 31,
         ('clear',): 31,
         ('lupus',): 31,
         ('bit',): 30,
         ('causes',): 30,
         ('attack',): 30,
         ('wilson',): 30,
         ('lungs',): 30,
         ('listen',): 30,
         ('pressure',): 30,
         ('hate',): 30,
         ('fact',): 29,
         ('assume',): 29,
         ('supposed',): 29,
         ('um',): 29,
         ('hope',): 29,
         ('stay',): 29,
         ('order',): 29,
         ('thinks',): 29,
         ('less',): 29,
         ('muscle',): 29,
         ('death',): 29,
         ('happen',): 29,
         ('feeling',): 29,
         ('open',): 29,
         ('skin',): 29,
         ('girl',): 28,
         ('white',): 28,
         ('hear',): 28,
         ('coming',): 28,
         ('cut',): 28,
         ('mother',): 28,
         ('thanks',): 28,
         ('fast',): 28,
         ('damn',): 28,
         ('checked',): 28,
         ('happy',): 28,
         ('everybody',): 27,
         ('knew',): 27,
         ('rate',): 27,
         ('running',): 27,
         ('dan',): 27,
         ('comes',): 27,
         ('drug',): 27,
         ('deal',): 27,
         ('bleeding',): 27,
         ('answer',): 26,
         ('treating',): 26,
         ('sometimes',): 26,
         ('started',): 26,
         ('under',): 26,
         ('kidneys',): 26,
         ('boy',): 26,
         ('true',): 26,
         ('late',): 25,
         ('side',): 25,
         ('shouldnt',): 25,
         ('office',): 25,
         ('today',): 25,
         ('cough',): 25,
         ('except',): 25,
         ('lives',): 25,
         ('giving',): 25,
         ('walk',): 25,
         ('perfect',): 25,
         ('saw',): 25,
         ('move',): 25,
         ('antibodies',): 25,
         ('everyone',): 25,
         ('iv',): 25,
         ('date',): 25,
         ('transplant',): 25,
         ('sleep',): 24,
         ('healthy',): 24,
         ('close',): 24,
         ('sleeping',): 24,
         ('reaction',): 24,
         ('figured',): 24,
         ('killing',): 24,
         ('definitely',): 24,
         ('world',): 24,
         ('anyone',): 24,
         ('opinion',): 24,
         ('usually',): 24,
         ('heard',): 24,
         ('crap',): 24,
         ('weird',): 24,
         ('place',): 24,
         ('send',): 24,
         ('sister',): 24,
         ('fun',): 23,
         ('none',): 23,
         ('interesting',): 23,
         ('cells',): 23,
         ('given',): 23,
         ('eyes',): 23,
         ('somebody',): 23,
         ('soon',): 23,
         ('ass',): 23,
         ('excuse',): 23,
         ('symptom',): 23,
         ('completely',): 23,
         ('ct',): 23,
         ('small',): 23,
         ('causing',): 23,
         ('pneumonia',): 23,
         ('sent',): 22,
         ('minute',): 22,
         ('throat',): 22,
         ('shot',): 22,
         ('medication',): 22,
         ('able',): 22,
         ('explain',): 22,
         ('immune',): 22,
         ('possible',): 22,
         ('meningitis',): 22,
         ('though',): 22,
         ('tested',): 22,
         ('gone',): 22,
         ('choice',): 22,
         ('twice',): 22,
         ('half',): 22,
         ('virus',): 22,
         ('list',): 22,
         ('pregnant',): 22,
         ('brother',): 22,
         ('telling',): 22,
         ('coma',): 22,
         ('play',): 22,
         ('friend',): 21,
         ('times',): 21,
         ('shell',): 21,
         ('read',): 21,
         ('red',): 21,
         ('mind',): 21,
         ('inflammation',): 21,
         ('nurse',): 21,
         ('food',): 21,
         ('married',): 21,
         ('waiting',): 21,
         ('wear',): 21,
         ('understand',): 21,
         ('low',): 21,
         ('failure',): 21,
         ('cardiac',): 21,
         ('wow',): 21,
         ('saved',): 21,
         ('hamilton',): 21,
         ('anthrax',): 21,
         ('month',): 20,
         ('died',): 20,
         ('together',): 20,
         ('blue',): 20,
         ('cat',): 20,
         ('excellent',): 20,
         ('face',): 20,
         ('scared',): 20,
         ('lied',): 20,
         ('funny',): 20,
         ('pants',): 20,
         ('stupid',): 20,
         ('count',): 20,
         ('explains',): 20,
         ('common',): 20,
         ('hands',): 20,
         ('bed',): 20,
         ('protect',): 20,
         ('hows',): 20,
         ('positive',): 20,
         ('board',): 20,
         ('boys',): 20,
         ('diet',): 20,
         ('poison',): 20,
         ('friends',): 19,
         ('goes',): 19,
         ('team',): 19,
         ('syndrome',): 19,
         ('busy',): 19,
         ('breathing',): 19,
         ('wheres',): 19,
         ('nose',): 19,
         ('turn',): 19,
         ('lawyer',): 19,
         ('against',): 19,
         ('air',): 19,
         ('floor',): 19,
         ('theory',): 19,
         ('likes',): 19,
         ('each',): 19,
         ('abdominal',): 19,
         ('difference',): 19,
         ('hit',): 19,
         ('seem',): 19,
         ('mark',): 19,
         ('fix',): 19,
         ('heres',): 19,
         ('works',): 19,
         ('tells',): 19,
         ('urine',): 19,
         ('bone',): 19,
         ('em',): 19,
         ('results',): 19,
         ('babies',): 19,
         ('fat',): 19,
         ('simple',): 18,
         ('age',): 18,
         ('stroke',): 18,
         ('5',): 18,
         ('looked',): 18,
         ('relax',): 18,
         ('later',): 18,
         ('hasnt',): 18,
         ('cold',): 18,
         ('important',): 18,
         ('werent',): 18,
         ('tomorrow',): 18,
         ('break',): 18,
         ('watch',): 18,
         ('trouble',): 18,
         ('dies',): 18,
         ('cure',): 18,
         ('100',): 18,
         ('between',): 18,
         ('business',): 18,
         ('jersey',): 18,
         ('push',): 18,
         ('young',): 18,
         ('mine',): 18,
         ('eye',): 18,
         ('brandon',): 18,
         ('hurts',): 18,
         ('honey',): 18,
         ('human',): 18,
         ('weight',): 18,
         ('water',): 18,
         ('eight',): 18,
         ('asking',): 18,
         ('killed',): 18,
         ('dinner',): 18,
         ('jessica',): 18,
         ('harvey',): 18,
         ('miss',): 17,
         ('absolutely',): 17,
         ('word',): 17,
         ('responding',): 17,
         ('screw',): 17,
         ('interested',): 17,
         ('truth',): 17,
         ('based',): 17,
         ('afraid',): 17,
         ('chest',): 17,
         ('decision',): 17,
         ('10',): 17,
         ('black',): 17,
         ('parkld',): 17,
         ('sounds',): 17,
         ('dangerous',): 17,
         ('crazy',): 17,
         ('wanna',): 17,
         ('sense',): 17,
         ('clothes',): 17,
         ('clots',): 17,
         ('pick',): 17,
         ('joey',): 17,
         ('lost',): 16,
         ('differential',): 16,
         ('20',): 16,
         ('worth',): 16,
         ('neck',): 16,
         ('changed',): 16,
         ('oxygen',): 16,
         ('during',): 16,
         ('father',): 16,
         ('needed',): 16,
         ('lucky',): 16,
         ('story',): 16,
         ('apparently',): 16,
         ('fight',): 16,
         ('idiot',): 16,
         ('shut',): 16,
         ('seen',): 16,
         ('xray',): 16,
         ('hair',): 16,
         ('seems',): 16,
         ('alone',): 16,
         ('worried',): 16,
         ('bucks',): 16,
         ('outside',): 16,
         ('revealed',): 16,
         ('takes',): 16,
         ('ms',): 16,
         ('anybody',): 16,
         ('hospitals',): 16,
         ('treated',): 16,
         ('win',): 16,
         ('stat',): 16,
         ('meeting',): 16,
         ('yours',): 16,
         ('gregg',): 16,
         ('tried',): 16,
         ('nope',): 16,
         ('remove',): 16,
         ('lose',): 16,
         ('form',): 16,
         ('bleed',): 16,
         ('buy',): 16,
         ('matt',): 16,
         ('john',): 16,
         ('speech',): 16,
         ('missed',): 15,
         ('tumors',): 15,
         ('set',): 15,
         ('showed',): 15,
         ('starts',): 15,
         ('notice',): 15,
         ('forget',): 15,
         ('elevated',): 15,
         ('nerve',): 15,
         ('conditions',): 15,
         ('mouth',): 15,
         ('cool',): 15,
         ('respiratory',): 15,
         ('living',): 15,
         ('bowel',): 15,
         ('hired',): 15,
         ('end',): 15,
         ('sons',): 15,
         ('trauma',): 15,
         ('changes',): 15,
         ('brought',): 15,
         ('bet',): 15,
         ('million',): 15,
         ('company',): 15,
         ('indicate',): 15,
         ('shows',): 15,
         ('hmm',): 15,
         ('known',): 15,
         ('ready',): 15,
         ('hed',): 15,
         ('number',): 15,
         ('myself',): 15,
         ('fault',): 15,
         ('arrest',): 15,
         ('signs',): 15,
         ('surgeon',): 15,
         ('elise',): 15,
         ('himself',): 15,
         ('paralysis',): 15,
         ('necrosis',): 15,
         ('lies',): 14,

In [17]:
print("Top 10 Unigrams:", unigram_counts.most_common(10))

Top 10 Unigrams: [(('<s>',), 16509), (('</s>',), 16509), (('the',), 3727), (('you',), 3426), (('to',), 2571), (('a',), 2558), (('i',), 2346), (('it',), 1409), (('and',), 1399), (('of',), 1223)]

### Bigram Model

In [18]:
# Build model
bigrams = build_ngrams(corpus, 2)

In [19]:
# Frequency count
bigram_counts = Counter(bigrams)

bigram_counts

Counter({('</s>', '<s>'): 16508,
         ('<s>', 'i'): 1183,
         ('<s>', 'you'): 876,
         ('<s>', 'no'): 477,
         ('<s>', 'the'): 467,
         ('<s>', 'its'): 461,
         ('<s>', 'what'): 393,
         ('you', '</s>'): 375,
         ('it', '</s>'): 368,
         ('<s>', 'im'): 350,
         ('<s>', 'and'): 324,
         ('<s>', 'well'): 314,
         ('<s>', 'he'): 274,
         ('in', 'the'): 257,
         ('<s>', 'if'): 249,
         ('me', '</s>'): 247,
         ('<s>', 'yeah'): 244,
         ('<s>', 'so'): 237,
         ('<s>', 'we'): 229,
         ('going', 'to'): 220,
         ('<s>', 'oh'): 218,
         ('<s>', 'youre'): 215,
         ('<s>', 'it'): 215,
         ('<s>', 'thats'): 214,
         ('right', '</s>'): 208,
         ('i', 'dont'): 205,
         ('<s>', 'hes'): 198,
         ('that', '</s>'): 193,
         ('him', '</s>'): 189,
         ('<s>', 'but'): 181,
         ('its', 'not'): 176,
         ('of', 'the'): 168,
         ('on', 'the'): 165,
         ('<s>', 'she'): 158,
         ('no', '</s>'): 155,
         ('you', 'know'): 153,
         ('i', 'was'): 146,
         ('to', 'be'): 144,
         ('<s>', 'why'): 143,
         ('do', 'you'): 143,
         ('are', 'you'): 142,
         ('<s>', 'shes'): 139,
         ('here', '</s>'): 134,
         ('want', 'to'): 133,
         ('to', 'the'): 128,
         ('<s>', 'this'): 128,
         ('<s>', 'how'): 126,
         ('up', '</s>'): 126,
         ('for', 'the'): 125,
         ('this', 'is'): 125,
         ('if', 'you'): 124,
         ('<s>', 'not'): 124,
         ('have', 'a'): 120,
         ('you', 'think'): 117,
         ('you', 'want'): 117,
         ('<s>', 'okay'): 117,
         ('yeah', '</s>'): 116,
         ('you', 'dont'): 115,
         ('to', 'do'): 113,
         ('<s>', 'they'): 112,
         ('you', 'have'): 112,
         ('have', 'to'): 107,
         ('to', 'get'): 106,
         ('need', 'to'): 105,
         ('her', '</s>'): 105,
         ('okay', '</s>'): 105,
         ('dr', 'house'): 103,
         ('<s>', 'theres'): 102,
         ('its', 'a'): 102,
         ('it', 'was'): 102,
         ('<s>', 'were'): 102,
         ('<s>', 'that'): 101,
         ('do', '</s>'): 99,
         ('<s>', 'whats'): 99,
         ('<s>', 'hey'): 98,
         ('<s>', 'dr'): 97,
         ('a', 'little'): 97,
         ('<s>', 'a'): 97,
         ('in', 'a'): 97,
         ('i', 'know'): 96,
         ('i', 'think'): 95,
         ('<s>', 'your'): 92,
         ('know', '</s>'): 92,
         ('you', 'were'): 92,
         ('im', 'not'): 91,
         ('<s>', 'do'): 91,
         ('i', 'have'): 90,
         ('this', '</s>'): 90,
         ('you', 'to'): 87,
         ('out', 'of'): 86,
         ('<s>', 'ill'): 86,
         ('house', '</s>'): 85,
         ('<s>', 'my'): 85,
         ('wrong', '</s>'): 84,
         ('on', '</s>'): 84,
         ('<s>', 'is'): 83,
         ('for', 'a'): 82,
         ('<s>', 'because'): 82,
         ('dont', 'know'): 82,
         ('you', 'can'): 80,
         ('and', 'the'): 79,
         ('what', '</s>'): 79,
         ('with', 'the'): 79,
         ('come', 'on'): 78,
         ('<s>', 'yes'): 77,
         ('<s>', 'maybe'): 77,
         ('do', 'it'): 77,
         ('is', 'a'): 76,
         ('<s>', 'just'): 76,
         ('out', '</s>'): 76,
         ('not', 'a'): 75,
         ('now', '</s>'): 74,
         ('could', 'be'): 74,
         ('one', 'of'): 74,
         ('them', '</s>'): 73,
         ('to', 'know'): 73,
         ('time', '</s>'): 73,
         ('i', 'need'): 71,
         ('i', 'cant'): 70,
         ('<s>', 'dont'): 70,
         ('<s>', 'right'): 69,
         ('fine', '</s>'): 69,
         ('<s>', 'his'): 69,
         ('did', 'you'): 67,
         ('im', 'sorry'): 67,
         ('youre', 'not'): 66,
         ('all', 'the'): 66,
         ('i', 'didnt'): 65,
         ('<s>', 'get'): 65,
         ('got', 'a'): 65,
         ('be', 'a'): 65,
         ('you', 'do'): 64,
         ('from', 'the'): 64,
         ('i', 'want'): 64,
         ('die', '</s>'): 64,
         ('i', 'am'): 64,
         ('we', 'have'): 63,
         ('<s>', '</s>'): 63,
         ('<s>', 'ive'): 63,
         ('<s>', 'then'): 63,
         ('<s>', 'all'): 62,
         ('i', 'can'): 62,
         ('there', '</s>'): 62,
         ('<s>', 'now'): 62,
         ('you', 'cant'): 61,
         ('all', 'right'): 61,
         ('one', '</s>'): 61,
         ('<s>', 'there'): 61,
         ('and', 'i'): 60,
         ('to', 'me'): 60,
         ('<s>', 'come'): 59,
         ('know', 'what'): 59,
         ('a', 'lot'): 58,
         ('back', '</s>'): 57,
         ('i', 'just'): 57,
         ('the', 'other'): 57,
         ('it', 'is'): 57,
         ('what', 'you'): 56,
         ('with', 'a'): 56,
         ('if', 'i'): 56,
         ('<s>', 'did'): 56,
         ('<s>', 'or'): 55,
         ('and', 'you'): 55,
         ('kind', 'of'): 55,
         ('again', '</s>'): 55,
         ('hes', 'not'): 55,
         ('go', '</s>'): 54,
         ('is', 'the'): 54,
         ('cancer', '</s>'): 53,
         ('he', 'was'): 53,
         ('you', 'are'): 53,
         ('what', 'are'): 52,
         ('in', 'your'): 52,
         ('me', 'to'): 52,
         ('nothing', '</s>'): 52,
         ('to', 'see'): 52,
         ('you', 'need'): 51,
         ('too', '</s>'): 51,
         ('we', 'can'): 51,
         ('is', '</s>'): 51,
         ('is', 'that'): 51,
         ('with', 'you'): 50,
         ('we', 'dont'): 50,
         ('good', '</s>'): 50,
         ('<s>', 'her'): 50,
         ('was', 'a'): 50,
         ('is', 'it'): 50,
         ('<s>', 'who'): 50,
         ('not', 'the'): 49,
         ('<s>', 'when'): 49,
         ('yes', '</s>'): 48,
         ('had', 'a'): 48,
         ('you', 'should'): 48,
         ('<s>', 'are'): 48,
         ('about', 'the'): 48,
         ('<s>', 'thank'): 48,
         ('would', 'have'): 48,
         ('what', 'do'): 48,
         ('of', 'course'): 48,
         ('to', 'make'): 47,
         ('of', 'your'): 47,
         ('thank', 'you'): 47,
         ('the', 'same'): 47,
         ('<s>', 'can'): 47,
         ('to', 'go'): 47,
         ('theres', 'no'): 47,
         ('<s>', 'good'): 46,
         ('doing', '</s>'): 46,
         ('sorry', '</s>'): 46,
         ('not', '</s>'): 46,
         ('<s>', 'in'): 46,
         ('he', 'doesnt'): 46,
         ('to', 'you'): 45,
         ('i', 'thought'): 45,
         ('talk', 'to'): 45,
         ('the', 'only'): 45,
         ('theres', 'a'): 45,
         ('dont', 'have'): 45,
         ('at', 'the'): 45,
         ('<s>', 'which'): 45,
         ('if', 'it'): 45,
         ('god', '</s>'): 45,
         ('not', 'going'): 44,
         ('on', 'a'): 44,
         ('if', 'we'): 44,
         ('the', 'blood'): 44,
         ('would', 'be'): 44,
         ('down', '</s>'): 44,
         ('<s>', 'could'): 44,
         ('what', 'i'): 44,
         ('you', 'guys'): 44,
         ('hey', '</s>'): 44,
         ('dont', 'want'): 43,
         ('if', 'its'): 43,
         ('problem', '</s>'): 43,
         ('better', '</s>'): 43,
         ('we', 'should'): 43,
         ('treatment', '</s>'): 42,
         ('people', '</s>'): 42,
         ('but', 'i'): 42,
         ('pain', '</s>'): 42,
         ('thing', '</s>'): 42,
         ('of', 'a'): 42,
         ('doctor', '</s>'): 41,
         ('youve', 'got'): 41,
         ('trying', 'to'): 41,
         ('about', '</s>'): 41,
         ('to', 'have'): 41,
         ('you', 'got'): 41,
         ('a', 'few'): 41,
         ('<s>', 'two'): 41,
         ('what', 'about'): 41,
         ('in', 'his'): 41,
         ('wrong', 'with'): 40,
         ('i', 'had'): 40,
         ('to', 'a'): 40,
         ('job', '</s>'): 40,
         ('because', 'you'): 40,
         ('she', 'was'): 40,
         ('you', 'doing'): 40,
         ('for', 'me'): 40,
         ('can', 'do'): 40,
         ('of', 'you'): 40,
         ('sure', '</s>'): 40,
         ('it', 'to'): 39,
         ('the', 'patient'): 39,
         ('it', 'could'): 39,
         ('sick', '</s>'): 39,
         ('is', 'not'): 39,
         ('you', 'just'): 39,
         ('symptoms', '</s>'): 39,
         ('to', '</s>'): 39,
         ('talking', 'about'): 39,
         ('<s>', 'uh'): 39,
         ('whats', 'wrong'): 38,
         ('for', 'you'): 38,
         ('dont', 'think'): 38,
         ('you', 'get'): 38,
         ('get', 'a'): 38,
         ('no', 'i'): 38,
         ('why', '</s>'): 38,
         ('way', '</s>'): 38,
         ('like', 'a'): 37,
         ('if', 'youre'): 37,
         ('<s>', 'lets'): 37,
         ('<s>', 'look'): 37,
         ('we', 'need'): 37,
         ('a', 'good'): 37,
         ('its', 'the'): 37,
         ('you', 'a'): 37,
         ('huh', '</s>'): 37,
         ('i', 'got'): 37,
         ('the', 'hospital'): 37,
         ('<s>', 'sorry'): 37,
         ('him', 'on'): 37,
         ('when', 'i'): 37,
         ('work', '</s>'): 36,
         ('did', '</s>'): 36,
         ('tell', 'me'): 36,
         ('us', '</s>'): 36,
         ('a', 'doctor'): 36,
         ('youre', 'gonna'): 36,
         ('life', '</s>'): 36,
         ('thats', 'not'): 36,
         ('do', 'the'): 36,
         ('patient', '</s>'): 36,
         ('<s>', 'house'): 36,
         ('off', '</s>'): 36,
         ('<s>', 'of'): 36,
         ('<s>', 'take'): 36,
         ('<s>', 'theyre'): 36,
         ('on', 'your'): 35,
         ('leg', '</s>'): 35,
         ('the', 'way'): 35,
         ('the', 'brain'): 35,
         ('you', 'said'): 35,
         ('to', 'take'): 35,
         ('something', '</s>'): 35,
         ('if', 'he'): 35,
         ('of', 'his'): 35,
         ('<s>', 'sure'): 35,
         ('<s>', 'weve'): 35,
         ('a', 'problem'): 34,
         ('hospital', '</s>'): 34,
         ('have', 'the'): 34,
         ('you', 'didnt'): 34,
         ('have', 'been'): 34,
         ('anything', '</s>'): 34,
         ('no', 'no'): 34,
         ('do', 'that'): 34,
         ('i', 'do'): 34,
         ('just', 'a'): 33,
         ('<s>', 'youve'): 33,
         ('could', 'have'): 33,
         ('to', 'talk'): 33,
         ('like', 'that'): 33,
         ('like', 'you'): 33,
         ('so', '</s>'): 33,
         ('when', 'you'): 33,
         ('thats', 'a'): 33,
         ('thats', 'why'): 33,
         ('<s>', 'hi'): 33,
         ('the', 'guy'): 33,
         ('surgery', '</s>'): 33,
         ('off', 'the'): 33,
         ('the', 'first'): 33,
         ('<s>', 'like'): 33,
         ('i', 'told'): 32,
         ('shes', 'not'): 32,
         ('which', 'is'): 32,
         ('at', 'least'): 32,
         ('have', 'you'): 32,
         ('you', 'had'): 32,
         ('else', '</s>'): 32,
         ('week', '</s>'): 32,
         ('back', 'to'): 32,
         ('should', 'be'): 32,
         ('need', 'a'): 32,
         ('room', '</s>'): 32,
         ('to', 'tell'): 31,
         ('that', 'you'): 31,
         ('whats', 'the'): 31,
         ('tests', '</s>'): 31,
         ('that', 'i'): 31,
         ('thats', 'what'): 31,
         ('and', 'then'): 31,
         ('of', 'them'): 31,
         ('not', 'gonna'): 31,
         ('to', 'him'): 31,
         ('you', 'could'): 31,
         ('and', 'a'): 31,
         ('would', 'you'): 31,
         ('him', 'to'): 31,
         ('ive', 'got'): 31,
         ('i', 'guess'): 31,
         ('know', 'how'): 31,
         ('why', 'are'): 30,
         ('tell', 'you'): 30,
         ('home', '</s>'): 30,
         ('chase', '</s>'): 30,
         ('he', 'has'): 30,
         ('weve', 'got'): 30,
         ('day', '</s>'): 30,
         ('brain', '</s>'): 30,
         ('a', 'couple'): 30,
         ('i', 'did'): 30,
         ('lot', 'of'): 30,
         ('look', 'at'): 30,
         ('youre', 'going'): 30,
         ('get', 'you'): 30,
         ('<s>', 'one'): 30,
         ('<s>', 'fine'): 30,
         ('do', 'i'): 30,
         ('great', '</s>'): 30,
         ('supposed', 'to'): 29,
         ('in', 'her'): 29,
         ('<s>', 'give'): 29,
         ('so', 'what'): 29,
         ('has', 'a'): 29,
         ('but', 'it'): 29,
         ('the', 'right'): 29,
         ('pills', '</s>'): 29,
         ('im', 'sure'): 29,
         ('<s>', 'actually'): 29,
         ('were', 'going'): 29,
         ('the', 'last'): 29,
         ('drugs', '</s>'): 29,
         ('<s>', 'please'): 28,
         ('know', 'that'): 28,
         ('a', 'patient'): 28,
         ('that', 'would'): 28,
         ('im', 'gonna'): 28,
         ('a', 'big'): 28,
         ('the', 'treatment'): 28,
         ('can', 'you'): 28,
         ('which', 'means'): 28,
         ('there', 'are'): 28,
         ('infection', '</s>'): 28,
         ('how', 'much'): 28,
         ('got', 'to'): 28,
         ('<s>', 'on'): 28,
         ('<s>', 'ok'): 27,
         ('but', 'you'): 27,
         ('<s>', 'see'): 27,
         ('guy', '</s>'): 27,
         ('tumor', '</s>'): 27,
         ('mri', '</s>'): 27,
         ('test', '</s>'): 27,
         ('im', 'going'): 27,
         ('case', '</s>'): 27,
         ('<s>', 'ah'): 27,
         ('i', 'mean'): 27,
         ('but', 'if'): 27,
         ('think', '</s>'): 27,
         ('looking', 'for'): 27,
         ('<s>', 'does'): 27,
         ('<s>', 'any'): 27,
         ('<s>', 'nothing'): 27,
         ('i', 'get'): 27,
         ('so', 'you'): 27,
         ('that', 'is'): 27,
         ('of', 'my'): 27,
         ('why', 'would'): 27,
         ('can', 'be'): 27,
         ('<s>', 'foreman'): 27,
         ('it', 'doesnt'): 27,
         ('cant', 'be'): 27,
         ('my', 'god'): 27,
         ('what', 'if'): 27,
         ('what', 'the'): 27,
         ('that', 'was'): 27,
         ('mom', '</s>'): 27,
         ('theres', 'nothing'): 26,
         ('what', 'did'): 26,
         ('but', '</s>'): 26,
         ('in', 'my'): 26,
         ('ago', '</s>'): 26,
         ('want', 'you'): 26,
         ('the', 'time'): 26,
         ('way', 'to'): 26,
         ('be', '</s>'): 26,
         ('and', 'if'): 26,
         ('oh', '</s>'): 26,
         ('will', 'be'): 26,
         ('might', 'be'): 26,
         ('get', 'the'): 26,
         ('all', 'of'): 26,
         ('i', 'said'): 26,
         ('gonna', 'be'): 26,
         ('right', 'now'): 26,
         ('do', 'this'): 26,
         ('foreman', '</s>'): 26,
         ('morning', '</s>'): 26,
         ('there', 'is'): 26,
         ('happened', '</s>'): 26,
         ('they', 'were'): 26,
         ('<s>', 'great'): 26,
         ('what', 'is'): 26,
         ('baby', '</s>'): 25,
         ('because', 'of'): 25,
         ('we', 'cant'): 25,
         ('talk', '</s>'): 25,
         ('disease', '</s>'): 25,
         ('screwed', 'up'): 25,
         ('in', '</s>'): 25,
         ('youre', 'right'): 25,
         ('want', 'me'): 25,
         ('but', 'the'): 25,
         ('must', 'have'): 25,
         ('there', 'was'): 25,
         ('i', 'should'): 25,
         ('dying', '</s>'): 25,
         ('<s>', 'for'): 25,
         ('wanted', 'to'): 25,
         ('dont', 'care'): 25,
         ('years', '</s>'): 25,
         ('make', 'a'): 25,
         ('take', 'the'): 25,
         ('to', 'save'): 25,
         ('kid', '</s>'): 25,
         ('<s>', 'go'): 25,
         ('are', '</s>'): 25,
         ('<s>', 'chase'): 25,
         ('her', 'to'): 25,
         ('im', 'a'): 24,
         ('of', 'us'): 24,
         ('to', 'think'): 24,
         ('the', 'one'): 24,
         ('dont', 'need'): 24,
         ('think', 'its'): 24,
         ('find', 'out'): 24,
         ('it', 'might'): 24,
         ('and', 'youre'): 24,
         ('need', 'you'): 24,
         ('were', 'gonna'): 24,
         ('what', 'happened'): 24,
         ('have', 'no'): 24,
         ('i', 'would'): 24,
         ('go', 'to'): 24,
         ('wants', 'to'): 24,
         ('doesnt', 'have'): 24,
         ('that', 'the'): 24,
         ('<s>', 'id'): 24,
         ('can', 'i'): 24,
         ('take', 'a'): 24,
         ('to', 'give'): 24,
         ('the', 'kid'): 24,
         ('<s>', 'start'): 24,
         ('no', 'idea'): 24,
         ('oh', 'my'): 24,
         ('going', 'on'): 24,
         ('and', '</s>'): 24,
         ('you', 'did'): 23,
         ('ok', '</s>'): 23,
         ('the', 'rest'): 23,
         ('a', 'tumor'): 23,
         ('get', 'her'): 23,
         ('because', 'i'): 23,
         ('by', 'the'): 23,
         ('<s>', 'three'): 23,
         ('how', 'long'): 23,
         ('do', 'we'): 23,
         ('<s>', 'where'): 23,
         ('through', 'the'): 23,
         ('please', '</s>'): 23,
         ('about', 'a'): 23,
         ('what', 'does'): 23,
         ('bad', '</s>'): 23,
         ('hurt', '</s>'): 23,
         ('got', 'it'): 23,
         ('i', '</s>'): 23,
         ('was', 'the'): 23,
         ('let', 'me'): 23,
         ('ive', 'been'): 23,
         ('on', 'her'): 23,
         ('and', 'your'): 22,
         ('figure', 'out'): 22,
         ('im', 'just'): 22,
         ('history', '</s>'): 22,
         ('is', 'why'): 22,
         ('i', 'assume'): 22,
         ('really', '</s>'): 22,
         ('better', 'than'): 22,
         ('as', 'a'): 22,
         ('have', '</s>'): 22,
         ('a', 'week'): 22,
         ('told', 'you'): 22,
         ('out', 'the'): 22,
         ('to', 'your'): 22,
         ('an', 'hour'): 22,
         ('am', 'i'): 22,
         ('<s>', 'as'): 22,
         ('able', 'to'): 22,
         ('think', 'you'): 22,
         ('make', 'it'): 22,
         ('everything', '</s>'): 22,
         ('<s>', 'have'): 22,
         ('hi', '</s>'): 22,
         ('see', 'you'): 22,
         ('money', '</s>'): 22,
         ('she', 'has'): 22,
         ('sex', '</s>'): 22,
         ('her', 'on'): 22,
         ('cuddy', '</s>'): 22,
         ('was', '</s>'): 22,
         ('enough', 'to'): 22,
         ('know', 'the'): 21,
         ('with', 'him'): 21,
         ('question', '</s>'): 21,
         ('is', 'she'): 21,
         ('and', 'we'): 21,
         ('but', 'im'): 21,
         ('call', '</s>'): 21,
         ('about', 'it'): 21,
         ('take', 'it'): 21,
         ('days', '</s>'): 21,
         ('a', 'heart'): 21,
         ('then', '</s>'): 21,
         ('up', 'to'): 21,
         ('to', 'her'): 21,
         ('give', 'you'): 21,
         ('well', 'i'): 21,
         ('up', 'with'): 21,
         ('mistake', '</s>'): 21,
         ('what', 'he'): 21,
         ('worse', '</s>'): 21,
         ('we', 'do'): 21,
         ('<s>', 'call'): 21,
         ('attack', '</s>'): 21,
         ('get', 'to'): 21,
         ('we', 'could'): 21,
         ('to', 'work'): 21,
         ('he', 'had'): 21,
         ('a', 'very'): 21,
         ('am', '</s>'): 21,
         ('<s>', 'unless'): 21,
         ('make', 'sure'): 21,
         ('it', 'up'): 21,
         ('point', '</s>'): 21,
         ('like', 'this'): 21,
         ('they', 'dont'): 21,
         ('<s>', 'very'): 21,
         ('cant', 'do'): 21,
         ('<s>', 'wait'): 21,
         ('with', 'your'): 21,
         ('get', 'it'): 21,
         ('give', 'him'): 21,
         ('youre', 'a'): 21,
         ('blood', '</s>'): 21,
         ('give', 'me'): 21,
         ('what', 'else'): 21,
         ('dead', '</s>'): 21,
         ('a', 'new'): 20,
         ('of', 'this'): 20,
         ('patients', '</s>'): 20,
         ('diagnosis', '</s>'): 20,
         ('medicine', '</s>'): 20,
         ('you', 'in'): 20,
         ('up', 'the'): 20,
         ('as', 'long'): 20,
         ('think', 'i'): 20,
         ('the', 'next'): 20,
         ('so', 'i'): 20,
         ('into', 'the'): 20,
         ('man', '</s>'): 20,
         ('care', 'about'): 20,
         ('in', 'here'): 20,
         ('couple', 'of'): 20,
         ('went', 'to'): 20,
         ('immune', 'system'): 20,
         ('were', 'not'): 20,
         ('ct', 'scan'): 20,
         ('even', 'if'): 20,
         ('does', 'it'): 20,
         ('<s>', 'either'): 20,
         ('as', 'you'): 20,
         ('<s>', 'got'): 20,
         ('looking', 'at'): 20,
         ('it', 'means'): 20,
         ('he', 'can'): 20,
         ('its', 'just'): 20,
         ('your', 'son'): 20,
         ('no', 'one'): 20,
         ('his', 'brain'): 20,
         ('<s>', 'tell'): 20,
         ('is', 'going'): 20,
         ('for', '</s>'): 20,
         ('well', '</s>'): 20,
         ('<s>', 'thanks'): 20,

In [20]:
# Conditional probabilities
bigram_prob = {
    (w1, w2): count / unigram_counts[(w1,)]
    for (w1, w2), count in bigram_counts.items()
}

bigram_prob

{('<s>', 'why'): 0.008661941971046095,
 ('why', 'are'): 0.09868421052631579,
 ('are', 'you'): 0.2915811088295688,
 ('you', 'late'): 0.0002918855808523059,
 ('late', '</s>'): 0.64,
 ('</s>', '<s>'): 0.9999394269792234,
 ('<s>', 'youre'): 0.013023199466957416,
 ('youre', 'not'): 0.12290502793296089,
 ('not', 'going'): 0.04793028322440087,
 ('going', 'to'): 0.7692307692307693,
 ('to', 'like'): 0.0019447685725398677,
 ('like', 'the'): 0.051771117166212535,
 ('the', 'answer'): 0.0016098738932116983,
 ('answer', '</s>'): 0.5,
 ('<s>', 'i'): 0.07165788357865406,
 ('i', 'already'): 0.002131287297527707,
 ('already', 'know'): 0.08163265306122448,
 ('know', 'the'): 0.040152963671128104,
 ('i', 'missed'): 0.002131287297527707,
 ('missed', 'the'): 0.13333333333333333,
 ('the', 'bus'): 0.002683123155352831,
 ('bus', '</s>'): 0.5384615384615384,
 ('i', 'dont'): 0.08738277919863598,
 ('dont', 'doubt'): 0.0017667844522968198,
 ('doubt', 'it'): 0.3333333333333333,
 ('it', 'no'): 0.0028388928317956,
 ('no', 'bus'): 0.001148105625717566,
 ('bus', 'stops'): 0.07692307692307693,
 ('stops', 'near'): 0.3333333333333333,
 ('near', 'brads'): 0.09090909090909091,
 ('brads', '</s>'): 1.0,
 ('<s>', 'you'): 0.053061966200254405,
 ('you', 'spent'): 0.0002918855808523059,
 ('spent', 'the'): 0.25,
 ('the', 'night'): 0.0021464985242822645,
 ('night', 'the'): 0.04081632653061224,
 ('the', 'alarm'): 0.00026831231553528306,
 ('alarm', 'didnt'): 1.0,
 ('didnt', 'work'): 0.019417475728155338,
 ('work', '</s>'): 0.3673469387755102,
 ('<s>', 'or'): 0.003331516142710037,
 ('or', 'maybe'): 0.017543859649122806,
 ('maybe', 'it'): 0.04054054054054054,
 ('it', 'did'): 0.0007097232079489,
 ('did', '</s>'): 0.14814814814814814,
 ('i', 'didnt'): 0.027706734867860187,
 ('didnt', 'sleep'): 0.009708737864077669,
 ('sleep', 'with'): 0.16666666666666666,
 ('with', 'him'): 0.0379746835443038,
 ('him', '</s>'): 0.34363636363636363,
 ('<s>', 'girl'): 6.0573020776546124e-05,
 ('girl', 'theres'): 0.03571428571428571,
 ('theres', '</s>'): 0.0045662100456621,
 ('<s>', 'theres'): 0.006178448119207705,
 ('theres', 'something'): 0.0365296803652968,
 ('something', 'either'): 0.006172839506172839,
 ('either', 'very'): 0.015625,
 ('very', 'wrong'): 0.027777777777777776,
 ('wrong', 'with'): 0.22346368715083798,
 ('with', 'you'): 0.09041591320072333,
 ('you', 'or'): 0.0011675423234092236,
 ('or', 'theres'): 0.007017543859649123,
 ('something', 'very'): 0.018518518518518517,
 ('theres', 'nothing'): 0.1187214611872146,
 ('nothing', 'wrong'): 0.05755395683453238,
 ('<s>', 'please'): 0.0016960445817432916,
 ('please', 'tell'): 0.09259259259259259,
 ('tell', 'me'): 0.21951219512195122,
 ('me', 'you'): 0.015408320493066256,
 ('you', 'know'): 0.0446584938704028,
 ('know', 'that'): 0.05353728489483748,
 ('that', 'for'): 0.008563273073263558,
 ('for', 'a'): 0.10211706102117062,
 ('a', 'fact'): 0.0007818608287724785,
 ('fact', '</s>'): 0.10344827586206896,
 ('<s>', 'melanie'): 6.0573020776546124e-05,
 ('melanie', 'i'): 0.5,
 ('i', 'gotta'): 0.004262574595055414,
 ('gotta', 'go'): 0.14754098360655737,
 ('go', '</s>'): 0.23376623376623376,
 ('youre', 'lying'): 0.01303538175046555,
 ('lying', 'arent'): 0.03225806451612903,
 ('arent', 'you'): 0.1568627450980392,
 ('you', '</s>'): 0.10945709281961472,
 ('i', 'wouldnt'): 0.005541346973572037,
 ('wouldnt', 'lie'): 0.013888888888888888,
 ('lie', 'to'): 0.24615384615384617,
 ('to', 'you'): 0.01750291715285881,
 ('<s>', 'good'): 0.0027863589557211217,
 ('good', 'morning'): 0.030837004405286344,
 ('morning', 'guys'): 0.024390243902439025,
 ('guys', '</s>'): 0.14634146341463414,
 ('morning', 'miss'): 0.024390243902439025,
 ('miss', 'rebecca'): 0.058823529411764705,
 ('rebecca', '</s>'): 0.7777777777777778,
 ('<s>', 'everybodys'): 0.00018171906232963838,
 ('everybodys', 'in'): 0.3333333333333333,
 ('in', 'their'): 0.006012024048096192,
 ('their', 'seats'): 0.010101010101010102,
 ('seats', '</s>'): 1.0,
 ('<s>', 'yes'): 0.004664122599794052,
 ('yes', '</s>'): 0.46153846153846156,
 ('<s>', 'ok'): 0.0016354715609667454,
 ('ok', 'sidney'): 0.018867924528301886,
 ('sidney', 'why'): 0.5,
 ('why', 'dont'): 0.02631578947368421,
 ('dont', 'you'): 0.026501766784452298,
 ('you', 'tell'): 0.004670169293636894,
 ('tell', 'us'): 0.09146341463414634,
 ('us', 'what'): 0.031446540880503145,
 ('what', 'you'): 0.06557377049180328,
 ('you', 'did'): 0.006713368359603036,
 ('did', 'this'): 0.024691358024691357,
 ('this', 'weekend'): 0.005772005772005772,
 ('weekend', '</s>'): 0.6,
 ('<s>', 'come'): 0.0035738082258162216,
 ('come', 'on'): 0.5064935064935064,
 ('on', 'sidney'): 0.001430615164520744,
 ('sidney', 'we'): 0.5,
 ('we', 'know'): 0.022788203753351208,
 ('know', 'youre'): 0.01338432122370937,
 ('not', 'shy'): 0.0010893246187363835,
 ('shy', '</s>'): 1.0,
 ('<s>', 'how'): 0.007632200617844812,
 ('how', 'come'): 0.0364963503649635,
 ('come', 'we'): 0.006493506493506494,
 ('we', 'always'): 0.0013404825737265416,
 ('always', 'have'): 0.011764705882352941,
 ('have', 'to'): 0.1402359108781127,
 ('to', 'tell'): 0.012057565149747181,
 ('tell', 'you'): 0.18292682926829268,
 ('you', 'what'): 0.0020431990659661413,
 ('what', 'we'): 0.0117096018735363,
 ('we', 'did'): 0.01876675603217158,
 ('did', 'and'): 0.00823045267489712,
 ('and', 'you'): 0.039313795568263046,
 ('you', 'never'): 0.003210741389375365,
 ('never', 'tell'): 0.007633587786259542,
 ('ok', 'i'): 0.05660377358490566,
 ('i', 'had'): 0.017050298380221655,
 ('had', 'a'): 0.2191780821917808,
 ('a', 'really'): 0.002736512900703675,
 ('really', 'great'): 0.019867549668874173,
 ('great', 'weekend'): 0.012987012987012988,
 ('weekend', 'but'): 0.1,
 ('but', 'you'): 0.05142857142857143,
 ('you', 'cant'): 0.01780502043199066,
 ('cant', 'tell'): 0.03461538461538462,
 ('tell', 'miss'): 0.006097560975609756,
 ('miss', 'melanie'): 0.058823529411764705,
 ('melanie', 'ok'): 0.5,
 ('ok', '</s>'): 0.4339622641509434,
 ('<s>', 'what'): 0.023805197165182628,
 ('what', 'did'): 0.03044496487119438,
 ('did', 'you'): 0.2757201646090535,
 ('you', 'do'): 0.018680677174547577,
 ('do', '</s>'): 0.14082503556187767,
 ('i', 'made'): 0.0038363171355498722,
 ('made', 'a'): 0.208955223880597,
 ('a', 'new'): 0.007818608287724784,
 ('new', 'friend'): 0.011111111111111112,
 ('friend', '</s>'): 0.38095238095238093,
 ('<s>', 'its'): 0.027924162577987764,
 ('its', 'so'): 0.004250797024442083,
 ('so', 'much'): 0.024489795918367346,
 ('much', 'fun'): 0.017699115044247787,
 ('fun', 'to'): 0.043478260869565216,
 ('to', 'make'): 0.018280824581874758,
 ('make', 'new'): 0.005780346820809248,
 ('new', 'friends'): 0.022222222222222223,
 ('friends', 'isnt'): 0.05263157894736842,
 ('isnt', 'it'): 0.14864864864864866,
 ('it', '</s>'): 0.26117814052519517,
 ('<s>', 'yeah'): 0.014779817069477254,
 ('yeah', 'yes'): 0.0034602076124567475,
 ('yes', 'etc'): 0.009615384615384616,
 ('etc', '</s>'): 1.0,
 ('<s>', 'absolutely'): 0.0006057302077654613,
 ('absolutely', '</s>'): 0.35294117647058826,
 ('you', 'should'): 0.014010507880910683,
 ('should', 'never'): 0.015625,
 ('never', 'keep'): 0.007633587786259542,
 ('keep', 'anything'): 0.013513513513513514,
 ('anything', 'from'): 0.03508771929824561,
 ('from', 'your'): 0.026785714285714284,
 ('your', 'parents'): 0.00831353919239905,
 ('parents', '</s>'): 0.30357142857142855,
 ('<s>', 'and'): 0.019625658731600944,
 ('and', 'i'): 0.04288777698355969,
 ('i', 'told'): 0.013640238704177323,
 ('told', 'them'): 0.08333333333333333,
 ('them', '</s>'): 0.41954022988505746,
 ('<s>', 'wh'): 0.00012114604155309225,
 ('wh', '</s>'): 0.5,
 ('<s>', 'c'): 6.0573020776546124e-05,
 ('c', 'a'): 0.1,
 ('a', 't'): 0.00039093041438623924,
 ('t', 'h'): 0.5,
 ('h', '</s>'): 0.3333333333333333,
 ('<s>', 'the'): 0.02828760070264704,
 ('the', '</s>'): 0.0018781862087469815,
 ('<s>', 'we'): 0.013871221757829063,
 ('that', 'word'): 0.0009514747859181732,
 ('word', 'the'): 0.058823529411764705,
 ('<s>', '29'): 6.0573020776546124e-05,
 ('29', 'year'): 0.6666666666666666,
 ('year', 'old'): 0.24489795918367346,
 ('old', 'female'): 0.022222222222222223,
 ('female', 'first'): 0.125,
 ('first', 'seizure'): 0.011494252873563218,
 ('seizure', 'one'): 0.07692307692307693,
 ('one', 'month'): 0.005361930294906166,
 ('month', 'ago'): 0.25,
 ('ago', 'lost'): 0.02040816326530612,
 ('lost', 'the'): 0.1875,
 ('the', 'ability'): 0.0013415615776764154,
 ('ability', 'to'): 0.8888888888888888,
 ('to', 'speak'): 0.002333722287047841,
 ('speak', '</s>'): 0.3333333333333333,
 ('<s>', 'babbled'): 6.0573020776546124e-05,
 ('babbled', 'like'): 1.0,
 ('like', 'a'): 0.1008174386920981,
 ('a', 'baby'): 0.004300234558248631,
 ('baby', '</s>'): 0.3968253968253968,
 ('<s>', 'present'): 6.0573020776546124e-05,
 ('present', 'deterioration'): 0.1,
 ('deterioration', 'of'): 0.5,
 ('of', 'mental'): 0.001635322976287817,
 ('mental', 'status'): 0.3,
 ('status', '</s>'): 0.375,
 ('<s>', 'see'): 0.0016354715609667454,
 ('see', 'that'): 0.010526315789473684,
 ('that', '</s>'): 0.18363463368220742,
 ('<s>', 'they'): 0.0067841783269731665,
 ('they', 'all'): 0.008620689655172414,
 ('all', 'assume'): 0.0025252525252525255,
 ('assume', 'im'): 0.034482758620689655,
 ('im', 'a'): 0.03636363636363636,
 ('a', 'patient'): 0.0109460516028147,
 ('patient', 'because'): 0.008064516129032258,
 ('because', 'of'): 0.102880658436214,
 ('of', 'this'): 0.016353229762878167,
 ('this', 'cane'): 0.001443001443001443,
 ('cane', '</s>'): 0.6363636363636364,
 ('<s>', 'so'): 0.014355805924041431,
 ('so', 'put'): 0.0020408163265306124,
 ('put', 'on'): 0.05952380952380952,
 ('on', 'a'): 0.06294706723891273,
 ('a', 'white'): 0.001563721657544957,
 ('white', 'coat'): 0.03571428571428571,
 ('coat', 'like'): 0.07692307692307693,
 ('the', 'rest'): 0.006171183257311511,
 ('rest', 'of'): 0.48484848484848486,
 ('of', 'us'): 0.019623875715453803,
 ('us', '</s>'): 0.22641509433962265,
 ('dont', 'want'): 0.07597173144876325,
 ('want', 'them'): 0.012987012987012988,
 ('them', 'to'): 0.04597701149425287,
 ('to', 'think'): 0.009334889148191364,
 ('think', 'im'): 0.05042016806722689,
 ('a', 'doctor'): 0.014073494917904612,
 ('doctor', '</s>'): 0.3942307692307692,
 ('you', 'see'): 0.004086398131932283,
 ('see', 'where'): 0.010526315789473684,
 ('where', 'the'): 0.11688311688311688,
 ('the', 'administration'): 0.00026831231553528306,
 ('administration', 'might'): 0.5,
 ('might', 'have'): 0.13131313131313133,
 ('have', 'a'): 0.15727391874180865,
 ('a', 'problem'): 0.013291634089132134,
 ('problem', 'with'): 0.16470588235294117,
 ('with', 'that'): 0.02531645569620253,
 ('that', 'attitude'): 0.0009514747859181732,
 ('attitude', '</s>'): 0.3333333333333333,
 ('<s>', 'people'): 0.0010903143739778303,
 ('people', 'dont'): 0.039735099337748346,
 ('want', 'a'): 0.03571428571428571,
 ('a', 'sick'): 0.001954652071931196,
 ('sick', 'doctor'): 0.010309278350515464,
 ('<s>', 'fair'): 6.0573020776546124e-05,
 ('fair', 'enough'): 0.2,
 ('enough', '</s>'): 0.2054794520547945,
 ('dont', 'like'): 0.024734982332155476,
 ('like', 'healthy'): 0.0027247956403269754,
 ('healthy', 'patients'): 0.041666666666666664,
 ('patients', '</s>'): 0.22988505747126436,
 ('the', '29'): 0.00026831231553528306,
 ('female', '</s>'): 0.25,
 ('the', 'one'): 0.006439495572846793,
 ('one', 'who'): 0.0160857908847185,
 ('who', 'cant'): 0.01775147928994083,
 ('cant', 'talk'): 0.011538461538461539,
 ('talk', 'i'): 0.01,
 ('i', 'liked'): 0.0008525149190110827,
 ('liked', 'that'): 0.1111111111111111,
 ('that', 'part'): 0.003805899143672693,
 ('part', '</s>'): 0.3225806451612903,
 ('<s>', 'shes'): 0.008419649887939912,
 ('shes', 'my'): 0.021897810218978103,
 ('my', 'cousin'): 0.0019157088122605363,
 ('cousin', '</s>'): 0.5,
 ('and', 'your'): 0.015725518227305217,
 ('your', 'cousin'): 0.004750593824228029,
 ('cousin', 'doesnt'): 0.125,
 ('doesnt', 'like'): 0.04522613065326633,
 ('the', 'diagnosis'): 0.0016098738932116983,
 ('diagnosis', '</s>'): 0.38461538461538464,
 ('wouldnt', 'either'): 0.013888888888888888,
 ('either', '</s>'): 0.296875,
 ('<s>', 'brain'): 0.00030286510388273063,
 ('brain', 'tumor'): 0.06956521739130435,
 ('tumor', 'shes'): 0.03076923076923077,
 ('shes', 'gonna'): 0.043795620437956206,
 ('gonna', 'die'): 0.058823529411764705,
 ('die', 'boring'): 0.009708737864077669,
 ('boring', '</s>'): 0.5,
 ('<s>', 'no'): 0.0288933309104125,
 ('no', 'wonder'): 0.0057405281285878304,
 ('wonder', 'youre'): 0.09090909090909091,
 ('youre', 'such'): 0.00186219739292365,
 ('such', 'a'): 0.45454545454545453,
 ('a', 'renowned'): 0.00039093041438623924,
 ('renowned', 'diagnostician'): 1.0,
 ('diagnostician', '</s>'): 0.5,
 ('you', 'dont'): 0.033566841798015175,
 ('dont', 'need'): 0.04240282685512368,
 ('need', 'to'): 0.41015625,
 ('to', 'actually'): 0.00038895371450797355,
 ('actually', 'know'): 0.02666666666666667,
 ('know', 'anything'): 0.0057361376673040155,
 ('anything', 'to'): 0.08771929824561403,
 ('to', 'figure'): 0.0027226760015558148,
 ('figure', 'out'): 0.5,
 ('out', 'whats'): 0.03485254691689008,
 ('whats', 'wrong'): 0.21839080459770116,
 ('wrong', '</s>'): 0.4692737430167598,
 ('youre', 'the'): 0.0335195530726257,
 ('the', 'oncologist'): 0.0005366246310705661,
 ('oncologist', 'im'): 0.2,
 ('im', 'just'): 0.03333333333333333,
 ('just', 'a'): 0.0616822429906542,
 ('a', 'lowly'): 0.00039093041438623924,
 ('lowly', 'infectious'): 1.0,
 ('infectious', 'disease'): 0.6666666666666666,
 ('disease', 'guy'): 0.01818181818181818,
 ('guy', '</s>'): 0.23893805309734514,
 ('<s>', 'hah'): 0.00036343812465927677,
 ('hah', 'yes'): 0.125,
 ('yes', 'just'): 0.009615384615384616,
 ('a', 'simple'): 0.002736512900703675,
 ('simple', 'country'): 0.05555555555555555,
 ('country', 'doctor'): 0.125,
 ('brain', 'tumors'): 0.008695652173913044,
 ('tumors', 'at'): 0.06666666666666667,
 ('at', 'her'): 0.022222222222222223,
 ('her', 'age'): 0.0046439628482972135,
 ('age', 'are'): 0.05555555555555555,
 ('are', 'highly'): 0.002053388090349076,
 ('highly', 'unlikely'): 0.4444444444444444,
 ('unlikely', '</s>'): 0.7142857142857143,
 ('shes', '29'): 0.0036496350364963502,
 ('29', 'whatever'): 0.3333333333333333,
 ('whatever', 'shes'): 0.03125,
 ('shes', 'got'): 0.051094890510948905,
 ('got', 'is'): 0.0027100271002710027,
 ('is', 'highly'): 0.0018796992481203006,
 ('<s>', 'protein'): 6.0573020776546124e-05,
 ('protein', 'markers'): 0.25,
 ('markers', 'for'): 0.5,
 ('for', 'the'): 0.15566625155666253,
 ('the', 'three'): 0.0016098738932116983,
 ('three', 'most'): 0.010752688172043012,
 ('most', 'prevalent'): 0.02,
 ('prevalent', 'brain'): 1.0,
 ('brain', 'cancers'): 0.008695652173913044,
 ('cancers', 'came'): 0.16666666666666666,
 ('came', 'up'): 0.08333333333333333,
 ('up', 'negative'): 0.0027100271002710027,
 ('negative', '</s>'): 0.3333333333333333,
 ('<s>', 'thats'): 0.012962626446180871,
 ('thats', 'an'): 0.010526315789473684,
 ('an', 'hmo'): 0.005555555555555556,
 ('hmo', 'lab'): 0.5,
 ('lab', 'you'): 0.030303030303030304,
 ('you', 'might'): 0.004670169293636894,
 ('might', 'as'): 0.0707070707070707,
 ('as', 'well'): 0.08085106382978724,
 ('well', 'have'): 0.007009345794392523,
 ('have', 'sent'): 0.003931847968545216,
 ('sent', 'it'): 0.045454545454545456,
 ('it', 'to'): 0.027679205110007096,
 ('to', 'a'): 0.015558148580318941,
 ('a', 'high'): 0.001954652071931196,
 ('high', 'school'): 0.34285714285714286,
 ('school', 'kid'): 0.027777777777777776,
 ('kid', 'with'): 0.03529411764705882,
 ('with', 'a'): 0.10126582278481013,
 ('a', 'chemistry'): 0.00039093041438623924,
 ('chemistry', 'set'): 1.0,
 ('set', '</s>'): 0.2,
 ('no', 'family'): 0.002296211251435132,
 ('family', 'history'): 0.35135135135135137,
 ('history', '</s>'): 0.3793103448275862,
 ('i', 'thought'): 0.01918158567774936,
 ('thought', 'your'): 0.01282051282051282,
 ('your', 'uncle'): 0.0011876484560570072,
 ('uncle', 'died'): 0.2,
 ('died', 'of'): 0.2,
 ('of', 'cancer'): 0.005723630417007359,
 ('cancer', '</s>'): 0.5760869565217391,
 ('<s>', 'other'): 0.0002422920831061845,
 ('other', 'side'): 0.015384615384615385,
 ('side', '</s>'): 0.36,
 ('no', 'environmental'): 0.001148105625717566,
 ('environmental', 'factors'): 0.1,
 ('factors', '</s>'): 1.0,
 ('<s>', 'that'): 0.006117875098431159,
 ('that', 'you'): 0.029495718363463368,
 ('know', 'of'): 0.0038240917782026767,
 ('of', '</s>'): 0.013900245298446443,
 ('and', 'shes'): 0.005003573981415297,
 ('shes', 'not'): 0.11678832116788321,
 ('not', 'responding'): 0.015250544662309368,
 ('responding', 'to'): 0.7647058823529411,
 ('to', 'radiation'): 0.0007779074290159471,
 ('radiation', 'treatment'): 0.2222222222222222,
 ('treatment', '</s>'): 0.42,
 ('<s>', 'none'): 0.0006663032285420074,
 ('none', 'of'): 0.5652173913043478,
 ('of', 'which'): 0.003270645952575634,
 ('which', 'is'): 0.2222222222222222,
 ('is', 'even'): 0.0009398496240601503,
 ('even', 'close'): 0.02586206896551724,
 ('close', 'to'): 0.375,
 ('to', 'dispositive'): 0.00038895371450797355,
 ('dispositive', '</s>'): 1.0,
 ('<s>', 'all'): 0.00375552728814586,
 ('all', 'it'): 0.007575757575757576,
 ('it', 'does'): 0.0042583392476933995,
 ('does', 'is'): 0.007633587786259542,
 ('is', 'raise'): 0.0009398496240601503,
 ('raise', 'one'): 0.16666666666666666,
 ('one', 'question'): 0.00804289544235925,
 ('question', '</s>'): 0.4772727272727273,
 ('<s>', 'your'): 0.005572717911442243,
 ('cousin', 'goes'): 0.125,
 ('goes', 'to'): 0.05263157894736842,
 ('to', 'an'): 0.0031116297160637884,
 ('hmo', '</s>'): 0.5,
 ('on', '</s>'): 0.12017167381974249,
 ('why', 'leave'): 0.003289473684210526,
 ('leave', 'all'): 0.02631578947368421,
 ('all', 'the'): 0.16666666666666666,
 ('the', 'fun'): 0.0008049369466058492,
 ('fun', 'for'): 0.043478260869565216,
 ('the', 'coroner'): 0.00026831231553528306,
 ('coroner', '</s>'): 1.0,
 ('<s>', 'whats'): 0.005996729056878067,
 ('whats', 'the'): 0.1781609195402299,
 ('the', 'point'): 0.00348806010195868,
 ('point', 'of'): 0.08771929824561403,
 ('of', 'putting'): 0.0008176614881439084,
 ('putting', 'together'): 0.1111111111111111,
 ('together', 'a'): 0.1,
 ('a', 'team'): 0.001563721657544957,
 ('team', 'if'): 0.05263157894736842,
 ('if', 'youre'): 0.05901116427432217,
 ('to', 'use'): 0.005056398288603656,
 ('use', 'them'): 0.023255813953488372,
 ('<s>', 'youve'): 0.001998909685626022,
 ('youve', 'got'): 0.39805825242718446,
 ('got', 'three'): 0.008130081300813009,
 ('three', 'overqualified'): 0.010752688172043012,
 ('overqualified', 'doctors'): 1.0,
 ('doctors', 'working'): 0.014925373134328358,
 ('working', 'for'): 0.07142857142857142,
 ('for', 'you'): 0.047322540473225407,
 ('<s>', 'getting'): 0.00030286510388273063,
 ('getting', 'bored'): 0.010752688172043012,
 ('bored', '</s>'): 0.5,
 ('its', 'a'): 0.10839532412327312,
 ('a', 'lesion'): 0.0011727912431587178,
 ('lesion', '</s>'): 0.16666666666666666,
 ('and', 'the'): 0.056468906361686916,
 ('the', 'big'): 0.004024684733029246,
 ('big', 'green'): 0.012195121951219513,
 ('green', 'thing'): 0.1111111111111111,
 ('thing', 'in'): 0.03418803418803419,
 ('in', 'the'): 0.2575150300601202,
 ('the', 'middle'): 0.0024148108398175474,
 ('middle', 'of'): 0.5384615384615384,
 ('of', 'the'): 0.1373671300081766,
 ('the', 'bigger'): 0.00026831231553528306,
 ('bigger', 'blue'): 0.1111111111111111,
 ('blue', 'thing'): 0.05,
 ('thing', 'on'): 0.017094017094017096,
 ('a', 'map'): 0.00039093041438623924,
 ('map', 'is'): 0.5,
 ('is', 'an'): 0.012218045112781954,
 ('an', 'island'): 0.002777777777777778,
 ('island', '</s>'): 0.25,
 ('i', 'was'): 0.06223358908780904,
 ('was', 'hoping'): 0.013559322033898305,
 ('hoping', 'for'): 0.23076923076923078,
 ('for', 'something'): 0.0037359900373599006,
 ('something', 'a'): 0.006172839506172839,
 ('a', 'bit'): 0.0050820953870211105,
 ('bit', 'more'): 0.06666666666666667,
 ('more', 'creative'): 0.005405405405405406,
 ('creative', '</s>'): 0.6666666666666666,
 ('<s>', 'shouldnt'): 0.00036343812465927677,
 ('shouldnt', 'we'): 0.12,
 ('we', 'be'): 0.0013404825737265416,
 ('be', 'speaking'): 0.0014814814814814814,
 ('speaking', 'to'): 0.4,

In [21]:
print("Top 10 Bigrams:", bigram_counts.most_common(10))

Top 10 Bigrams: [(('</s>', '<s>'), 16508), (('<s>', 'i'), 1183), (('<s>', 'you'), 876), (('<s>', 'no'), 477), (('<s>', 'the'), 467), (('<s>', 'its'), 461), (('<s>', 'what'), 393), (('you', '</s>'), 375), (('it', '</s>'), 368), (('<s>', 'im'), 350)]

### Trigram Model

In [22]:
# Build model
trigrams = build_ngrams(corpus, 3)

In [23]:
# Frequency count
trigram_counts = Counter(trigrams)

trigram_counts

Counter({('</s>', '<s>', 'i'): 1183,
         ('</s>', '<s>', 'you'): 876,
         ('</s>', '<s>', 'no'): 477,
         ('</s>', '<s>', 'the'): 467,
         ('</s>', '<s>', 'its'): 461,
         ('</s>', '<s>', 'what'): 393,
         ('you', '</s>', '<s>'): 375,
         ('it', '</s>', '<s>'): 368,
         ('</s>', '<s>', 'im'): 350,
         ('</s>', '<s>', 'and'): 324,
         ('</s>', '<s>', 'well'): 314,
         ('</s>', '<s>', 'he'): 274,
         ('</s>', '<s>', 'if'): 249,
         ('me', '</s>', '<s>'): 247,
         ('</s>', '<s>', 'yeah'): 244,
         ('</s>', '<s>', 'so'): 237,
         ('</s>', '<s>', 'we'): 229,
         ('</s>', '<s>', 'oh'): 218,
         ('</s>', '<s>', 'youre'): 215,
         ('</s>', '<s>', 'it'): 215,
         ('</s>', '<s>', 'thats'): 214,
         ('right', '</s>', '<s>'): 208,
         ('</s>', '<s>', 'hes'): 198,
         ('that', '</s>', '<s>'): 193,
         ('him', '</s>', '<s>'): 189,
         ('</s>', '<s>', 'but'): 181,
         ('</s>', '<s>', 'she'): 158,
         ('no', '</s>', '<s>'): 155,
         ('</s>', '<s>', 'why'): 142,
         ('</s>', '<s>', 'shes'): 139,
         ('<s>', 'i', 'dont'): 134,
         ('here', '</s>', '<s>'): 134,
         ('</s>', '<s>', 'this'): 128,
         ('</s>', '<s>', 'how'): 126,
         ('up', '</s>', '<s>'): 126,
         ('</s>', '<s>', 'not'): 124,
         ('<s>', 'no', '</s>'): 121,
         ('</s>', '<s>', 'okay'): 117,
         ('yeah', '</s>', '<s>'): 116,
         ('</s>', '<s>', 'they'): 112,
         ('her', '</s>', '<s>'): 105,
         ('okay', '</s>', '<s>'): 105,
         ('</s>', '<s>', 'theres'): 102,
         ('</s>', '<s>', 'were'): 102,
         ('</s>', '<s>', 'that'): 101,
         ('do', '</s>', '<s>'): 99,
         ('</s>', '<s>', 'whats'): 99,
         ('</s>', '<s>', 'hey'): 98,
         ('</s>', '<s>', 'dr'): 97,
         ('</s>', '<s>', 'a'): 97,
         ('<s>', 'yeah', '</s>'): 93,
         ('</s>', '<s>', 'your'): 92,
         ('know', '</s>', '<s>'): 92,
         ('</s>', '<s>', 'do'): 91,
         ('this', '</s>', '<s>'): 90,
         ('<s>', 'its', 'not'): 88,
         ('</s>', '<s>', 'ill'): 86,
         ('house', '</s>', '<s>'): 85,
         ('</s>', '<s>', 'my'): 85,
         ('wrong', '</s>', '<s>'): 84,
         ('on', '</s>', '<s>'): 84,
         ('</s>', '<s>', 'is'): 83,
         ('</s>', '<s>', 'because'): 82,
         ('what', '</s>', '<s>'): 79,
         ('</s>', '<s>', 'yes'): 77,
         ('</s>', '<s>', 'maybe'): 77,
         ('</s>', '<s>', 'just'): 76,
         ('out', '</s>', '<s>'): 76,
         ('<s>', 'i', 'was'): 74,
         ('now', '</s>', '<s>'): 74,
         ('them', '</s>', '<s>'): 73,
         ('time', '</s>', '<s>'): 73,
         ('</s>', '<s>', 'dont'): 70,
         ('</s>', '<s>', 'right'): 69,
         ('fine', '</s>', '<s>'): 69,
         ('<s>', 'you', 'know'): 69,
         ('</s>', '<s>', 'his'): 69,
         ('</s>', '<s>', 'get'): 65,
         ('<s>', 'im', 'not'): 64,
         ('die', '</s>', '<s>'): 64,
         ('<s>', 'this', 'is'): 64,
         ('</s>', '<s>', '</s>'): 63,
         ('<s>', '</s>', '<s>'): 63,
         ('</s>', '<s>', 'ive'): 63,
         ('</s>', '<s>', 'then'): 63,
         ('</s>', '<s>', 'all'): 62,
         ('there', '</s>', '<s>'): 62,
         ('</s>', '<s>', 'now'): 62,
         ('one', '</s>', '<s>'): 61,
         ('</s>', '<s>', 'there'): 61,
         ('</s>', '<s>', 'come'): 59,
         ('<s>', 'i', 'think'): 59,
         ('<s>', 'do', 'you'): 58,
         ('<s>', 'come', 'on'): 57,
         ('back', '</s>', '<s>'): 57,
         ('</s>', '<s>', 'did'): 56,
         ('</s>', '<s>', 'or'): 55,
         ('again', '</s>', '<s>'): 55,
         ('go', '</s>', '<s>'): 54,
         ('cancer', '</s>', '<s>'): 53,
         ('nothing', '</s>', '<s>'): 52,
         ('<s>', 'i', 'know'): 52,
         ('<s>', 'you', 'dont'): 51,
         ('too', '</s>', '<s>'): 51,
         ('is', '</s>', '<s>'): 51,
         ('</s>', '<s>', 'her'): 50,
         ('</s>', '<s>', 'who'): 50,
         ('<s>', 'dr', 'house'): 49,
         ('dr', 'house', '</s>'): 49,
         ('good', '</s>', '<s>'): 49,
         ('</s>', '<s>', 'when'): 49,
         ('yes', '</s>', '<s>'): 48,
         ('<s>', 'its', 'a'): 48,
         ('</s>', '<s>', 'are'): 48,
         ('</s>', '<s>', 'thank'): 48,
         ('<s>', 'if', 'you'): 47,
         ('</s>', '<s>', 'can'): 47,
         ('do', 'it', '</s>'): 47,
         ('</s>', '<s>', 'good'): 46,
         ('<s>', 'im', 'sorry'): 46,
         ('doing', '</s>', '<s>'): 46,
         ('sorry', '</s>', '<s>'): 46,
         ('not', '</s>', '<s>'): 46,
         ('</s>', '<s>', 'in'): 46,
         ('<s>', 'okay', '</s>'): 46,
         ('<s>', 'you', 'think'): 45,
         ('<s>', 'you', 'have'): 45,
         ('you', 'want', 'to'): 45,
         ('</s>', '<s>', 'which'): 45,
         ('god', '</s>', '<s>'): 45,
         ('down', '</s>', '<s>'): 44,
         ('</s>', '<s>', 'could'): 44,
         ('<s>', 'hey', '</s>'): 44,
         ('hey', '</s>', '<s>'): 44,
         ('problem', '</s>', '<s>'): 43,
         ('all', 'right', '</s>'): 43,
         ('better', '</s>', '<s>'): 43,
         ('<s>', 'i', 'cant'): 43,
         ('treatment', '</s>', '<s>'): 42,
         ('people', '</s>', '<s>'): 42,
         ('pain', '</s>', '<s>'): 42,
         ('thing', '</s>', '<s>'): 42,
         ('doctor', '</s>', '<s>'): 41,
         ('about', '</s>', '<s>'): 41,
         ('<s>', 'i', 'need'): 41,
         ('what', 'are', 'you'): 41,
         ('</s>', '<s>', 'two'): 41,
         ('i', 'dont', 'know'): 41,
         ('not', 'going', 'to'): 40,
         ('job', '</s>', '<s>'): 40,
         ('<s>', 'i', 'want'): 40,
         ('<s>', 'what', 'are'): 40,
         ('<s>', 'what', '</s>'): 40,
         ('sure', '</s>', '<s>'): 40,
         ('<s>', 'you', 'want'): 39,
         ('<s>', 'thank', 'you'): 39,
         ('sick', '</s>', '<s>'): 39,
         ('symptoms', '</s>', '<s>'): 39,
         ('to', '</s>', '<s>'): 39,
         ('</s>', '<s>', 'uh'): 39,
         ('why', '</s>', '<s>'): 38,
         ('<s>', 'i', 'just'): 38,
         ('way', '</s>', '<s>'): 38,
         ('<s>', 'are', 'you'): 37,
         ('</s>', '<s>', 'lets'): 37,
         ('</s>', '<s>', 'look'): 37,
         ('huh', '</s>', '<s>'): 37,
         ('</s>', '<s>', 'sorry'): 37,
         ('<s>', 'youre', 'not'): 36,
         ('work', '</s>', '<s>'): 36,
         ('did', '</s>', '<s>'): 36,
         ('us', '</s>', '<s>'): 36,
         ('life', '</s>', '<s>'): 36,
         ('patient', '</s>', '<s>'): 36,
         ('<s>', 'right', '</s>'): 36,
         ('</s>', '<s>', 'house'): 36,
         ('to', 'me', '</s>'): 36,
         ('off', '</s>', '<s>'): 36,
         ('</s>', '<s>', 'of'): 36,
         ('</s>', '<s>', 'take'): 36,
         ('</s>', '<s>', 'theyre'): 36,
         ('<s>', 'i', 'have'): 35,
         ('leg', '</s>', '<s>'): 35,
         ('with', 'you', '</s>'): 35,
         ('<s>', 'what', 'do'): 35,
         ('something', '</s>', '<s>'): 35,
         ('<s>', 'what', 'about'): 35,
         ('</s>', '<s>', 'sure'): 35,
         ('<s>', 'it', 'was'): 35,
         ('</s>', '<s>', 'weve'): 35,
         ('hospital', '</s>', '<s>'): 34,
         ('<s>', 'you', 'cant'): 34,
         ('anything', '</s>', '<s>'): 34,
         ('<s>', 'i', 'didnt'): 33,
         ('</s>', '<s>', 'youve'): 33,
         ('so', '</s>', '<s>'): 33,
         ('</s>', '<s>', 'hi'): 33,
         ('<s>', 'of', 'course'): 33,
         ('surgery', '</s>', '<s>'): 33,
         ('</s>', '<s>', 'like'): 33,
         ('else', '</s>', '<s>'): 32,
         ('thank', 'you', '</s>'): 32,
         ('<s>', 'no', 'i'): 32,
         ('week', '</s>', '<s>'): 32,
         ('room', '</s>', '<s>'): 32,
         ('<s>', 'yes', '</s>'): 31,
         ('come', 'on', '</s>'): 31,
         ('tests', '</s>', '<s>'): 31,
         ('are', 'you', 'doing'): 31,
         ('im', 'sorry', '</s>'): 31,
         ('<s>', 'did', 'you'): 31,
         ('<s>', 'i', 'thought'): 30,
         ('its', 'not', 'a'): 30,
         ('home', '</s>', '<s>'): 30,
         ('chase', '</s>', '<s>'): 30,
         ('you', 'have', 'a'): 30,
         ('day', '</s>', '<s>'): 30,
         ('brain', '</s>', '<s>'): 30,
         ('</s>', '<s>', 'one'): 30,
         ('</s>', '<s>', 'fine'): 30,
         ('great', '</s>', '<s>'): 30,
         ('<s>', 'all', 'right'): 29,
         ('</s>', '<s>', 'give'): 29,
         ('for', 'me', '</s>'): 29,
         ('<s>', 'theres', 'no'): 29,
         ('<s>', 'hes', 'not'): 29,
         ('pills', '</s>', '<s>'): 29,
         ('what', 'do', 'you'): 29,
         ('</s>', '<s>', 'actually'): 29,
         ('drugs', '</s>', '<s>'): 29,
         ('</s>', '<s>', 'please'): 28,
         ('<s>', 'and', 'the'): 28,
         ('need', 'to', 'know'): 28,
         ('a', 'lot', 'of'): 28,
         ('youre', 'going', 'to'): 28,
         ('infection', '</s>', '<s>'): 28,
         ('<s>', 'we', 'have'): 28,
         ('</s>', '<s>', 'on'): 28,
         ('</s>', '<s>', 'ok'): 27,
         ('</s>', '<s>', 'see'): 27,
         ('i', 'dont', 'want'): 27,
         ('guy', '</s>', '<s>'): 27,
         ('tumor', '</s>', '<s>'): 27,
         ('mri', '</s>', '<s>'): 27,
         ('test', '</s>', '<s>'): 27,
         ('case', '</s>', '<s>'): 27,
         ('</s>', '<s>', 'ah'): 27,
         ('think', '</s>', '<s>'): 27,
         ('</s>', '<s>', 'does'): 27,
         ('</s>', '<s>', 'any'): 27,
         ('</s>', '<s>', 'nothing'): 27,
         ('<s>', 'why', '</s>'): 27,
         ('</s>', '<s>', 'foreman'): 27,
         ('to', 'do', '</s>'): 27,
         ('mom', '</s>', '<s>'): 27,
         ('why', 'are', 'you'): 26,
         ('to', 'you', '</s>'): 26,
         ('but', '</s>', '<s>'): 26,
         ('ago', '</s>', '<s>'): 26,
         ('it', 'could', 'be'): 26,
         ('be', '</s>', '<s>'): 26,
         ('<s>', 'oh', '</s>'): 26,
         ('oh', '</s>', '<s>'): 26,
         ('<s>', 'thats', 'why'): 26,
         ('do', 'you', 'think'): 26,
         ('foreman', '</s>', '<s>'): 26,
         ('morning', '</s>', '<s>'): 26,
         ('happened', '</s>', '<s>'): 26,
         ('were', 'going', 'to'): 26,
         ('</s>', '<s>', 'great'): 26,
         ('baby', '</s>', '<s>'): 25,
         ('talk', '</s>', '<s>'): 25,
         ('disease', '</s>', '<s>'): 25,
         ('in', '</s>', '<s>'): 25,
         ('dying', '</s>', '<s>'): 25,
         ('</s>', '<s>', 'for'): 25,
         ('years', '</s>', '<s>'): 25,
         ('kid', '</s>', '<s>'): 25,
         ('</s>', '<s>', 'go'): 25,
         ('are', '</s>', '<s>'): 25,
         ('</s>', '<s>', 'chase'): 25,
         ('i', 'need', 'to'): 25,
         ('want', 'you', 'to'): 24,
         ('want', 'me', 'to'): 24,
         ('you', 'doing', '</s>'): 24,
         ('<s>', 'so', 'what'): 24,
         ('dont', 'want', 'to'): 24,
         ('</s>', '<s>', 'id'): 24,
         ('</s>', '<s>', 'start'): 24,
         ('<s>', 'fine', '</s>'): 24,
         ('<s>', 'and', 'you'): 24,
         ('and', '</s>', '<s>'): 24,
         ('<s>', 'you', 'are'): 24,
         ('ok', '</s>', '<s>'): 23,
         ('<s>', 'what', 'did'): 23,
         ('for', 'you', '</s>'): 23,
         ('<s>', 'if', 'we'): 23,
         ('</s>', '<s>', 'three'): 23,
         ('</s>', '<s>', 'where'): 23,
         ('please', '</s>', '<s>'): 23,
         ('going', 'to', 'be'): 23,
         ('bad', '</s>', '<s>'): 23,
         ('hurt', '</s>', '<s>'): 23,
         ('i', 'want', 'to'): 23,
         ('i', '</s>', '<s>'): 23,
         ('<s>', 'oh', 'my'): 23,
         ('<s>', 'you', 'should'): 22,
         ('history', '</s>', '<s>'): 22,
         ('i', 'dont', 'think'): 22,
         ('really', '</s>', '<s>'): 22,
         ('have', '</s>', '<s>'): 22,
         ('<s>', 'you', 'can'): 22,
         ('i', 'have', 'a'): 22,
         ('dont', 'know', '</s>'): 22,
         ('</s>', '<s>', 'as'): 22,
         ('<s>', 'if', 'its'): 22,
         ('everything', '</s>', '<s>'): 22,
         ('</s>', '<s>', 'have'): 22,
         ('<s>', 'you', 'were'): 22,
         ('<s>', 'is', 'that'): 22,
         ('<s>', 'hi', '</s>'): 22,
         ('hi', '</s>', '<s>'): 22,
         ('money', '</s>', '<s>'): 22,
         ('<s>', 'he', 'doesnt'): 22,
         ('sex', '</s>', '<s>'): 22,
         ('going', 'to', 'do'): 22,
         ('do', 'that', '</s>'): 22,
         ('cuddy', '</s>', '<s>'): 22,
         ('was', '</s>', '<s>'): 22,
         ('im', 'going', 'to'): 22,
         ('is', 'it', '</s>'): 22,
         ('question', '</s>', '<s>'): 21,
         ('call', '</s>', '<s>'): 21,
         ('<s>', 'we', 'need'): 21,
         ('days', '</s>', '<s>'): 21,
         ('then', '</s>', '<s>'): 21,
         ('<s>', 'you', 'said'): 21,
         ('whats', 'wrong', 'with'): 21,
         ('mistake', '</s>', '<s>'): 21,
         ('worse', '</s>', '<s>'): 21,
         ('</s>', '<s>', 'call'): 21,
         ('attack', '</s>', '<s>'): 21,
         ('am', '</s>', '<s>'): 21,
         ('</s>', '<s>', 'unless'): 21,
         ('<s>', 'thats', 'what'): 21,
         ('point', '</s>', '<s>'): 21,
         ('<s>', 'i', 'am'): 21,
         ('like', 'that', '</s>'): 21,
         ('</s>', '<s>', 'very'): 21,
         ('</s>', '<s>', 'wait'): 21,
         ('<s>', 'whats', 'wrong'): 21,
         ('<s>', 'what', 'if'): 21,
         ('blood', '</s>', '<s>'): 21,
         ('dead', '</s>', '<s>'): 21,
         ('<s>', 'could', 'be'): 21,
         ('oh', 'my', 'god'): 21,
         ('<s>', 'why', 'are'): 20,
         ('patients', '</s>', '<s>'): 20,
         ('diagnosis', '</s>', '<s>'): 20,
         ('medicine', '</s>', '<s>'): 20,
         ('<s>', 'i', 'assume'): 20,
         ('<s>', 'thats', 'not'): 20,
         ('we', 'need', 'to'): 20,
         ('<s>', 'i', 'mean'): 20,
         ('you', 'need', 'to'): 20,
         ('<s>', 'well', 'i'): 20,
         ('man', '</s>', '<s>'): 20,
         ('i', 'am', '</s>'): 20,
         ('<s>', 'thats', 'a'): 20,
         ('</s>', '<s>', 'either'): 20,
         ('</s>', '<s>', 'got'): 20,
         ('</s>', '<s>', 'tell'): 20,
         ('for', '</s>', '<s>'): 20,
         ('well', '</s>', '<s>'): 20,
         ('</s>', '<s>', 'thanks'): 20,
         ('</s>', '<s>', 'um'): 20,
         ('do', 'you', 'want'): 20,
         ('clear', '</s>', '<s>'): 20,
         ('going', 'on', '</s>'): 20,
         ('wait', '</s>', '<s>'): 20,
         ('you', 'do', '</s>'): 19,
         ('<s>', 'and', 'i'): 19,
         ('either', '</s>', '<s>'): 19,
         ('<s>', 'i', 'can'): 19,
         ('</s>', '<s>', 'to'): 19,
         ('</s>', '<s>', 'nice'): 19,
         ('as', 'long', 'as'): 19,
         ('</s>', '<s>', 'itll'): 19,
         ('<s>', 'yeah', 'i'): 19,
         ('i', 'know', '</s>'): 19,
         ('it', 'was', 'a'): 19,
         ('</s>', '<s>', 'at'): 19,
         ('you', 'know', 'what'): 19,
         ('<s>', 'it', 'could'): 19,
         ('done', '</s>', '<s>'): 19,
         ('more', '</s>', '<s>'): 19,
         ('said', '</s>', '<s>'): 19,
         ('<s>', 'i', 'told'): 19,
         ('<s>', 'why', 'would'): 19,
         ('<s>', 'if', 'i'): 19,
         ('dont', '</s>', '<s>'): 19,
         ('yet', '</s>', '<s>'): 19,
         ('away', '</s>', '<s>'): 19,
         ('<s>', 'i', 'got'): 19,
         ('<s>', 'i', 'guess'): 19,
         ('</s>', '<s>', 'stop'): 19,
         ('<s>', 'what', 'is'): 19,
         ('my', 'god', '</s>'): 19,
         ('night', '</s>', '<s>'): 19,
         ('</s>', '<s>', 'people'): 18,
         ('<s>', 'whats', 'the'): 18,
         ('this', 'is', 'a'): 18,
         ('nice', '</s>', '<s>'): 18,
         ('i', 'want', 'you'): 18,
         ('want', '</s>', '<s>'): 18,
         ('you', 'want', 'me'): 18,
         ('</s>', '<s>', 'cant'): 18,
         ('steroids', '</s>', '<s>'): 18,
         ('old', '</s>', '<s>'): 18,
         ('you', 'know', '</s>'): 18,
         ('fast', '</s>', '<s>'): 18,
         ('<s>', 'well', 'you'): 18,
         ('a', 'couple', 'of'): 18,
         ('<s>', 'i', 'had'): 18,
         ('name', '</s>', '<s>'): 18,
         ('</s>', '<s>', 'next'): 18,
         ('hour', '</s>', '<s>'): 18,
         ('<s>', 'theres', 'a'): 18,
         ('happen', '</s>', '<s>'): 18,
         ('all', '</s>', '<s>'): 18,
         ('<s>', 'its', 'the'): 18,
         ('</s>', '<s>', 'let'): 18,
         ('<s>', 'were', 'going'): 18,
         ('</s>', '<s>', 'wow'): 18,
         ('liver', '</s>', '<s>'): 18,
         ('</s>', '<s>', 'mr'): 18,
         ('with', 'him', '</s>'): 17,
         ('parents', '</s>', '<s>'): 17,
         ('of', '</s>', '<s>'): 17,
         ('</s>', '<s>', 'too'): 17,
         ('today', '</s>', '<s>'): 17,
         ('you', 'dont', 'have'): 17,
         ('you', 'have', 'to'): 17,
         ('<s>', 'so', 'you'): 17,
         ('problems', '</s>', '<s>'): 17,
         ('is', 'not', 'a'): 17,
         ('<s>', 'the', 'only'): 17,
         ('<s>', 'but', 'you'): 17,
         ('stuff', '</s>', '<s>'): 17,
         ('care', '</s>', '<s>'): 17,
         ('lie', '</s>', '<s>'): 17,
         ('screwed', 'up', '</s>'): 17,
         ('</s>', '<s>', 'dan'): 17,
         ('<s>', 'it', 'doesnt'): 17,
         ('<s>', 'what', 'does'): 17,
         ('<s>', 'can', 'i'): 17,
         ('<s>', 'sure', '</s>'): 17,
         ('two', '</s>', '<s>'): 17,
         ('</s>', '<s>', 'hows'): 17,
         ('</s>', '<s>', 'doesnt'): 17,
         ('on', 'the', 'other'): 17,
         ('</s>', '<s>', 'listen'): 17,
         ('system', '</s>', '<s>'): 17,
         ('say', '</s>', '<s>'): 17,
         ('whats', 'going', 'on'): 17,
         ('</s>', '<s>', 'even'): 17,
         ('</s>', '<s>', 'youll'): 17,
         ('<s>', 'if', 'it'): 17,
         ('</s>', '<s>', 'some'): 17,
         ('late', '</s>', '<s>'): 16,
         ('<s>', 'theres', 'nothing'): 16,
         ('the', 'rest', 'of'): 16,
         ('whats', 'wrong', '</s>'): 16,
         ('if', 'we', 'dont'): 16,
         ('scan', '</s>', '<s>'): 16,
         ('normal', '</s>', '<s>'): 16,
         ('</s>', '<s>', 'really'): 16,
         ('if', 'you', 'dont'): 16,
         ('cameron', '</s>', '<s>'): 16,
         ('i', 'have', 'to'): 16,
         ('to', 'talk', 'to'): 16,
         ('do', 'you', 'have'): 16,
         ('yourself', '</s>', '<s>'): 16,
         ('<s>', 'what', 'happened'): 16,
         ('</s>', '<s>', 'would'): 16,
         ('</s>', '<s>', 'whoa'): 16,
         ('<s>', 'you', 'got'): 16,
         ('<s>', 'can', 'you'): 16,
         ('see', '</s>', '<s>'): 16,
         ('<s>', 'how', 'long'): 16,
         ('it', 'is', '</s>'): 16,
         ('hours', '</s>', '<s>'): 16,
         ('of', 'them', '</s>'): 16,
         ('<s>', 'no', 'no'): 16,
         ('cant', '</s>', '<s>'): 16,
         ('<s>', 'have', 'you'): 16,
         ('does', '</s>', '<s>'): 16,
         ('idea', '</s>', '<s>'): 16,
         ('want', 'to', 'know'): 16,
         ('<s>', 'he', 'was'): 16,
         ('<s>', 'you', 'need'): 16,
         ('<s>', 'oh', 'god'): 16,
         ('<s>', 'we', 'should'): 16,
         ('working', '</s>', '<s>'): 16,
         ('is', 'going', 'to'): 16,
         ('to', 'be', 'a'): 16,
         ('condition', '</s>', '<s>'): 16,
         ('the', 'other', 'hand'): 16,
         ('do', 'you', 'know'): 16,
         ('<s>', 'ive', 'got'): 16,
         ('be', 'fine', '</s>'): 16,
         ('true', '</s>', '<s>'): 16,
         ('</s>', '<s>', 'nope'): 16,
         ('<s>', 'on', 'the'): 16,
         ('<s>', 'weve', 'got'): 16,
         ('pneumonia', '</s>', '<s>'): 16,
         ('a', 'doctor', '</s>'): 15,
         ('enough', '</s>', '<s>'): 15,
         ('</s>', '<s>', 'excellent'): 15,
         ('you', 'want', '</s>'): 15,
         ('minute', '</s>', '<s>'): 15,
         ('<s>', 'shes', 'not'): 15,
         ('<s>', 'and', 'if'): 15,
         ('</s>', '<s>', 'pretty'): 15,
         ('thanks', '</s>', '<s>'): 15,
         ('in', 'here', '</s>'): 15,
         ('be', 'able', 'to'): 15,
         ('a', 'week', '</s>'): 15,
         ('<s>', 'no', 'its'): 15,
         ('<s>', 'well', 'if'): 15,
         ('</s>', '<s>', 'our'): 15,
         ('dan', '</s>', '<s>'): 15,

In [24]:
# Conditional probabilities for trigrams
trigram_prob = {
    (w1, w2, w3): count / bigram_counts[(w1, w2)]
    for (w1, w2, w3), count in trigram_counts.items()
    if bigram_counts[(w1, w2)] > 0
}

trigram_prob

{('<s>', 'why', 'are'): 0.13986013986013987,
 ('why', 'are', 'you'): 0.8666666666666667,
 ('are', 'you', 'late'): 0.007042253521126761,
 ('you', 'late', '</s>'): 1.0,
 ('late', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'youre'): 0.013023988369275503,
 ('<s>', 'youre', 'not'): 0.16744186046511628,
 ('youre', 'not', 'going'): 0.13636363636363635,
 ('not', 'going', 'to'): 0.9090909090909091,
 ('going', 'to', 'like'): 0.01818181818181818,
 ('to', 'like', 'the'): 0.2,
 ('like', 'the', 'answer'): 0.05263157894736842,
 ('the', 'answer', '</s>'): 0.8333333333333334,
 ('answer', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'i'): 0.0716622243760601,
 ('<s>', 'i', 'already'): 0.0033812341504649195,
 ('i', 'already', 'know'): 0.2,
 ('already', 'know', 'the'): 0.25,
 ('know', 'the', 'answer'): 0.047619047619047616,
 ('<s>', 'i', 'missed'): 0.0033812341504649195,
 ('i', 'missed', 'the'): 0.4,
 ('missed', 'the', 'bus'): 1.0,
 ('the', 'bus', '</s>'): 0.7,
 ('bus', '</s>', '<s>'): 1.0,
 ('<s>', 'i', 'dont'): 0.1132713440405748,
 ('i', 'dont', 'doubt'): 0.004878048780487805,
 ('dont', 'doubt', 'it'): 1.0,
 ('doubt', 'it', 'no'): 0.3333333333333333,
 ('it', 'no', 'bus'): 0.25,
 ('no', 'bus', 'stops'): 1.0,
 ('bus', 'stops', 'near'): 1.0,
 ('stops', 'near', 'brads'): 1.0,
 ('near', 'brads', '</s>'): 1.0,
 ('brads', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'you'): 0.05306518051853647,
 ('<s>', 'you', 'spent'): 0.001141552511415525,
 ('you', 'spent', 'the'): 1.0,
 ('spent', 'the', 'night'): 1.0,
 ('the', 'night', 'the'): 0.125,
 ('night', 'the', 'alarm'): 0.5,
 ('the', 'alarm', 'didnt'): 1.0,
 ('alarm', 'didnt', 'work'): 1.0,
 ('didnt', 'work', '</s>'): 0.75,
 ('work', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'or'): 0.0033317179549309426,
 ('<s>', 'or', 'maybe'): 0.07272727272727272,
 ('or', 'maybe', 'it'): 0.4,
 ('maybe', 'it', 'did'): 0.16666666666666666,
 ('it', 'did', '</s>'): 1.0,
 ('did', '</s>', '<s>'): 1.0,
 ('<s>', 'i', 'didnt'): 0.027895181741335588,
 ('i', 'didnt', 'sleep'): 0.03076923076923077,
 ('didnt', 'sleep', 'with'): 0.5,
 ('sleep', 'with', 'him'): 0.25,
 ('with', 'him', '</s>'): 0.8095238095238095,
 ('him', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'girl'): 6.05766900896535e-05,
 ('<s>', 'girl', 'theres'): 1.0,
 ('girl', 'theres', '</s>'): 1.0,
 ('theres', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'theres'): 0.006178822389144657,
 ('<s>', 'theres', 'something'): 0.029411764705882353,
 ('theres', 'something', 'either'): 0.125,
 ('something', 'either', 'very'): 1.0,
 ('either', 'very', 'wrong'): 1.0,
 ('very', 'wrong', 'with'): 0.6666666666666666,
 ('wrong', 'with', 'you'): 0.2,
 ('with', 'you', 'or'): 0.02,
 ('you', 'or', 'theres'): 0.25,
 ('or', 'theres', 'something'): 0.5,
 ('theres', 'something', 'very'): 0.125,
 ('something', 'very', 'wrong'): 0.3333333333333333,
 ('wrong', 'with', 'him'): 0.325,
 ('<s>', 'theres', 'nothing'): 0.1568627450980392,
 ('theres', 'nothing', 'wrong'): 0.23076923076923078,
 ('nothing', 'wrong', 'with'): 1.0,
 ('</s>', '<s>', 'please'): 0.001696147322510298,
 ('<s>', 'please', 'tell'): 0.10714285714285714,
 ('please', 'tell', 'me'): 1.0,
 ('tell', 'me', 'you'): 0.1388888888888889,
 ('me', 'you', 'know'): 0.1,
 ('you', 'know', 'that'): 0.032679738562091505,
 ('know', 'that', 'for'): 0.03571428571428571,
 ('that', 'for', 'a'): 0.1111111111111111,
 ('for', 'a', 'fact'): 0.012195121951219513,
 ('a', 'fact', '</s>'): 0.5,
 ('fact', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'melanie'): 6.05766900896535e-05,
 ('<s>', 'melanie', 'i'): 1.0,
 ('melanie', 'i', 'gotta'): 1.0,
 ('i', 'gotta', 'go'): 0.3,
 ('gotta', 'go', '</s>'): 0.7777777777777778,
 ('go', '</s>', '<s>'): 1.0,
 ('<s>', 'youre', 'lying'): 0.013953488372093023,
 ('youre', 'lying', 'arent'): 0.14285714285714285,
 ('lying', 'arent', 'you'): 1.0,
 ('arent', 'you', '</s>'): 0.625,
 ('you', '</s>', '<s>'): 1.0,
 ('<s>', 'i', 'wouldnt'): 0.0084530853761623,
 ('i', 'wouldnt', 'lie'): 0.07692307692307693,
 ('wouldnt', 'lie', 'to'): 1.0,
 ('lie', 'to', 'you'): 0.0625,
 ('to', 'you', '</s>'): 0.5777777777777777,
 ('</s>', '<s>', 'good'): 0.002786527744124061,
 ('<s>', 'good', 'morning'): 0.10869565217391304,
 ('good', 'morning', 'guys'): 0.14285714285714285,
 ('morning', 'guys', '</s>'): 1.0,
 ('guys', '</s>', '<s>'): 1.0,
 ('good', 'morning', 'miss'): 0.14285714285714285,
 ('morning', 'miss', 'rebecca'): 1.0,
 ('miss', 'rebecca', '</s>'): 1.0,
 ('rebecca', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'everybodys'): 0.0001817300702689605,
 ('<s>', 'everybodys', 'in'): 0.3333333333333333,
 ('everybodys', 'in', 'their'): 1.0,
 ('in', 'their', 'seats'): 0.16666666666666666,
 ('their', 'seats', '</s>'): 1.0,
 ('seats', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'yes'): 0.004664405136903319,
 ('<s>', 'yes', '</s>'): 0.4025974025974026,
 ('yes', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'ok'): 0.0016355706324206445,
 ('<s>', 'ok', 'sidney'): 0.037037037037037035,
 ('ok', 'sidney', 'why'): 1.0,
 ('sidney', 'why', 'dont'): 1.0,
 ('why', 'dont', 'you'): 0.75,
 ('dont', 'you', 'tell'): 0.06666666666666667,
 ('you', 'tell', 'us'): 0.0625,
 ('tell', 'us', 'what'): 0.2,
 ('us', 'what', 'you'): 0.4,
 ('what', 'you', 'did'): 0.07142857142857142,
 ('you', 'did', 'this'): 0.043478260869565216,
 ('did', 'this', 'weekend'): 0.16666666666666666,
 ('this', 'weekend', '</s>'): 0.75,
 ('weekend', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'come'): 0.0035740247152895566,
 ('<s>', 'come', 'on'): 0.9661016949152542,
 ('come', 'on', 'sidney'): 0.01282051282051282,
 ('on', 'sidney', 'we'): 1.0,
 ('sidney', 'we', 'know'): 1.0,
 ('we', 'know', 'youre'): 0.058823529411764705,
 ('know', 'youre', 'not'): 0.2857142857142857,
 ('youre', 'not', 'shy'): 0.015151515151515152,
 ('not', 'shy', '</s>'): 1.0,
 ('shy', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'how'): 0.007632662951296341,
 ('<s>', 'how', 'come'): 0.05555555555555555,
 ('how', 'come', 'we'): 0.1,
 ('come', 'we', 'always'): 1.0,
 ('we', 'always', 'have'): 1.0,
 ('always', 'have', 'to'): 1.0,
 ('have', 'to', 'tell'): 0.028037383177570093,
 ('to', 'tell', 'you'): 0.12903225806451613,
 ('tell', 'you', 'what'): 0.13333333333333333,
 ('you', 'what', 'we'): 0.14285714285714285,
 ('what', 'we', 'did'): 0.2,
 ('we', 'did', 'and'): 0.14285714285714285,
 ('did', 'and', 'you'): 0.5,
 ('and', 'you', 'never'): 0.05454545454545454,
 ('you', 'never', 'tell'): 0.09090909090909091,
 ('never', 'tell', 'us'): 1.0,
 ('you', 'did', '</s>'): 0.17391304347826086,
 ('<s>', 'ok', 'i'): 0.07407407407407407,
 ('ok', 'i', 'had'): 0.3333333333333333,
 ('i', 'had', 'a'): 0.175,
 ('had', 'a', 'really'): 0.020833333333333332,
 ('a', 'really', 'great'): 0.14285714285714285,
 ('really', 'great', 'weekend'): 0.3333333333333333,
 ('great', 'weekend', 'but'): 1.0,
 ('weekend', 'but', 'you'): 1.0,
 ('but', 'you', 'cant'): 0.037037037037037035,
 ('you', 'cant', 'tell'): 0.04918032786885246,
 ('cant', 'tell', 'miss'): 0.1111111111111111,
 ('tell', 'miss', 'melanie'): 1.0,
 ('miss', 'melanie', 'ok'): 1.0,
 ('melanie', 'ok', '</s>'): 1.0,
 ('ok', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'what'): 0.023806639205233827,
 ('<s>', 'what', 'did'): 0.058524173027989825,
 ('what', 'did', 'you'): 0.4230769230769231,
 ('did', 'you', 'do'): 0.05970149253731343,
 ('you', 'do', '</s>'): 0.296875,
 ('do', '</s>', '<s>'): 1.0,
 ('<s>', 'i', 'made'): 0.00507185122569738,
 ('i', 'made', 'a'): 0.5555555555555556,
 ('made', 'a', 'new'): 0.07142857142857142,
 ('a', 'new', 'friend'): 0.05,
 ('new', 'friend', '</s>'): 1.0,
 ('friend', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'its'): 0.027925854131330263,
 ('<s>', 'its', 'so'): 0.006507592190889371,
 ('its', 'so', 'much'): 0.25,
 ('so', 'much', 'fun'): 0.08333333333333333,
 ('much', 'fun', 'to'): 0.5,
 ('fun', 'to', 'make'): 1.0,
 ('to', 'make', 'new'): 0.02127659574468085,
 ('make', 'new', 'friends'): 1.0,
 ('new', 'friends', 'isnt'): 0.5,
 ('friends', 'isnt', 'it'): 1.0,
 ('isnt', 'it', '</s>'): 0.8181818181818182,
 ('it', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'yeah'): 0.014780712381875455,
 ('<s>', 'yeah', 'yes'): 0.004098360655737705,
 ('yeah', 'yes', 'etc'): 1.0,
 ('yes', 'etc', '</s>'): 1.0,
 ('etc', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'absolutely'): 0.000605766900896535,
 ('<s>', 'absolutely', '</s>'): 0.6,
 ('absolutely', '</s>', '<s>'): 1.0,
 ('<s>', 'you', 'should'): 0.02511415525114155,
 ('you', 'should', 'never'): 0.020833333333333332,
 ('should', 'never', 'keep'): 0.3333333333333333,
 ('never', 'keep', 'anything'): 1.0,
 ('keep', 'anything', 'from'): 1.0,
 ('anything', 'from', 'your'): 0.25,
 ('from', 'your', 'parents'): 0.16666666666666666,
 ('your', 'parents', '</s>'): 0.42857142857142855,
 ('parents', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'and'): 0.019626847589047734,
 ('<s>', 'and', 'i'): 0.05864197530864197,
 ('and', 'i', 'told'): 0.05,
 ('i', 'told', 'them'): 0.15625,
 ('told', 'them', '</s>'): 0.14285714285714285,
 ('them', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'wh'): 0.000121153380179307,
 ('<s>', 'wh', '</s>'): 0.5,
 ('wh', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'c'): 6.05766900896535e-05,
 ('<s>', 'c', 'a'): 1.0,
 ('c', 'a', 't'): 1.0,
 ('a', 't', 'h'): 1.0,
 ('t', 'h', '</s>'): 1.0,
 ('h', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'the'): 0.028289314271868184,
 ('<s>', 'the', '</s>'): 0.0021413276231263384,
 ('the', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'we'): 0.013872062030530652,
 ('<s>', 'we', 'know'): 0.013100436681222707,
 ('we', 'know', 'that'): 0.11764705882352941,
 ('know', 'that', 'word'): 0.03571428571428571,
 ('that', 'word', 'the'): 1.0,
 ('word', 'the', '</s>'): 1.0,
 ('</s>', '<s>', '29'): 6.05766900896535e-05,
 ('<s>', '29', 'year'): 1.0,
 ('29', 'year', 'old'): 1.0,
 ('year', 'old', 'female'): 0.16666666666666666,
 ('old', 'female', 'first'): 0.5,
 ('female', 'first', 'seizure'): 1.0,
 ('first', 'seizure', 'one'): 1.0,
 ('seizure', 'one', 'month'): 1.0,
 ('one', 'month', 'ago'): 0.5,
 ('month', 'ago', 'lost'): 0.2,
 ('ago', 'lost', 'the'): 1.0,
 ('lost', 'the', 'ability'): 0.3333333333333333,
 ('the', 'ability', 'to'): 0.8,
 ('ability', 'to', 'speak'): 0.25,
 ('to', 'speak', '</s>'): 0.5,
 ('speak', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'babbled'): 6.05766900896535e-05,
 ('<s>', 'babbled', 'like'): 1.0,
 ('babbled', 'like', 'a'): 1.0,
 ('like', 'a', 'baby'): 0.02702702702702703,
 ('a', 'baby', '</s>'): 0.45454545454545453,
 ('baby', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'present'): 6.05766900896535e-05,
 ('<s>', 'present', 'deterioration'): 1.0,
 ('present', 'deterioration', 'of'): 1.0,
 ('deterioration', 'of', 'mental'): 1.0,
 ('of', 'mental', 'status'): 0.5,
 ('mental', 'status', '</s>'): 0.3333333333333333,
 ('status', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'see'): 0.0016355706324206445,
 ('<s>', 'see', 'that'): 0.07407407407407407,
 ('see', 'that', '</s>'): 0.5,
 ('that', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'they'): 0.006784589290041192,
 ('<s>', 'they', 'all'): 0.017857142857142856,
 ('they', 'all', 'assume'): 0.3333333333333333,
 ('all', 'assume', 'im'): 1.0,
 ('assume', 'im', 'a'): 1.0,
 ('im', 'a', 'patient'): 0.041666666666666664,
 ('a', 'patient', 'because'): 0.03571428571428571,
 ('patient', 'because', 'of'): 1.0,
 ('because', 'of', 'this'): 0.04,
 ('of', 'this', 'cane'): 0.05,
 ('this', 'cane', '</s>'): 1.0,
 ('cane', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'so'): 0.01435667555124788,
 ('<s>', 'so', 'put'): 0.004219409282700422,
 ('so', 'put', 'on'): 1.0,
 ('put', 'on', 'a'): 0.6,
 ('on', 'a', 'white'): 0.022727272727272728,
 ('a', 'white', 'coat'): 0.25,
 ('white', 'coat', 'like'): 1.0,
 ('coat', 'like', 'the'): 1.0,
 ('like', 'the', 'rest'): 0.05263157894736842,
 ('the', 'rest', 'of'): 0.6956521739130435,
 ('rest', 'of', 'us'): 0.0625,
 ('of', 'us', '</s>'): 0.4166666666666667,
 ('us', '</s>', '<s>'): 1.0,
 ('i', 'dont', 'want'): 0.13170731707317074,
 ('dont', 'want', 'them'): 0.023255813953488372,
 ('want', 'them', 'to'): 0.25,
 ('them', 'to', 'think'): 0.125,
 ('to', 'think', 'im'): 0.041666666666666664,
 ('think', 'im', 'a'): 0.1111111111111111,
 ('im', 'a', 'doctor'): 0.20833333333333334,
 ('a', 'doctor', '</s>'): 0.4166666666666667,
 ('doctor', '</s>', '<s>'): 1.0,
 ('<s>', 'you', 'see'): 0.0045662100456621,
 ('you', 'see', 'where'): 0.07142857142857142,
 ('see', 'where', 'the'): 1.0,
 ('where', 'the', 'administration'): 0.1111111111111111,
 ('the', 'administration', 'might'): 1.0,
 ('administration', 'might', 'have'): 1.0,
 ('might', 'have', 'a'): 0.15384615384615385,
 ('have', 'a', 'problem'): 0.09166666666666666,
 ('a', 'problem', 'with'): 0.38235294117647056,
 ('problem', 'with', 'that'): 0.2857142857142857,
 ('with', 'that', 'attitude'): 0.07142857142857142,
 ('that', 'attitude', '</s>'): 1.0,
 ('attitude', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'people'): 0.001090380421613763,
 ('<s>', 'people', 'dont'): 0.16666666666666666,
 ('people', 'dont', 'want'): 0.16666666666666666,
 ('dont', 'want', 'a'): 0.023255813953488372,
 ('want', 'a', 'sick'): 0.09090909090909091,
 ('a', 'sick', 'doctor'): 0.2,
 ('sick', 'doctor', '</s>'): 1.0,
 ('</s>', '<s>', 'fair'): 6.05766900896535e-05,
 ('<s>', 'fair', 'enough'): 1.0,
 ('fair', 'enough', '</s>'): 1.0,
 ('enough', '</s>', '<s>'): 1.0,
 ('i', 'dont', 'like'): 0.03902439024390244,
 ('dont', 'like', 'healthy'): 0.07142857142857142,
 ('like', 'healthy', 'patients'): 1.0,
 ('healthy', 'patients', '</s>'): 1.0,
 ('patients', '</s>', '<s>'): 1.0,
 ('<s>', 'the', '29'): 0.0021413276231263384,
 ('the', '29', 'year'): 1.0,
 ('old', 'female', '</s>'): 0.5,
 ('female', '</s>', '<s>'): 1.0,
 ('<s>', 'the', 'one'): 0.006423982869379015,
 ('the', 'one', 'who'): 0.16666666666666666,
 ('one', 'who', 'cant'): 0.16666666666666666,
 ('who', 'cant', 'talk'): 0.6666666666666666,
 ('cant', 'talk', 'i'): 0.3333333333333333,
 ('talk', 'i', 'liked'): 1.0,
 ('i', 'liked', 'that'): 0.5,
 ('liked', 'that', 'part'): 1.0,
 ('that', 'part', '</s>'): 0.5,
 ('part', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'shes'): 0.008420159922461836,
 ('<s>', 'shes', 'my'): 0.02158273381294964,
 ('shes', 'my', 'cousin'): 0.16666666666666666,
 ('my', 'cousin', '</s>'): 1.0,
 ('cousin', '</s>', '<s>'): 1.0,
 ('<s>', 'and', 'your'): 0.027777777777777776,
 ('and', 'your', 'cousin'): 0.045454545454545456,
 ('your', 'cousin', 'doesnt'): 0.25,
 ('cousin', 'doesnt', 'like'): 1.0,
 ('doesnt', 'like', 'the'): 0.2222222222222222,
 ('like', 'the', 'diagnosis'): 0.05263157894736842,
 ('the', 'diagnosis', '</s>'): 0.5,
 ('diagnosis', '</s>', '<s>'): 1.0,
 ('i', 'wouldnt', 'either'): 0.07692307692307693,
 ('wouldnt', 'either', '</s>'): 1.0,
 ('either', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'brain'): 0.0003028834504482675,
 ('<s>', 'brain', 'tumor'): 0.4,
 ('brain', 'tumor', 'shes'): 0.125,
 ('tumor', 'shes', 'gonna'): 0.5,
 ('shes', 'gonna', 'die'): 0.4166666666666667,
 ('gonna', 'die', 'boring'): 0.07142857142857142,
 ('die', 'boring', '</s>'): 1.0,
 ('boring', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'no'): 0.02889508117276472,
 ('<s>', 'no', 'wonder'): 0.0041928721174004195,
 ('no', 'wonder', 'youre'): 0.2,
 ('wonder', 'youre', 'such'): 1.0,
 ('youre', 'such', 'a'): 1.0,
 ('such', 'a', 'renowned'): 0.2,
 ('a', 'renowned', 'diagnostician'): 1.0,
 ('renowned', 'diagnostician', '</s>'): 1.0,
 ('diagnostician', '</s>', '<s>'): 1.0,
 ('<s>', 'you', 'dont'): 0.05821917808219178,
 ('you', 'dont', 'need'): 0.0782608695652174,
 ('dont', 'need', 'to'): 0.4583333333333333,
 ('need', 'to', 'actually'): 0.009523809523809525,
 ('to', 'actually', 'know'): 1.0,
 ('actually', 'know', 'anything'): 0.5,
 ('know', 'anything', 'to'): 0.3333333333333333,
 ('anything', 'to', 'figure'): 0.1,
 ('to', 'figure', 'out'): 0.8571428571428571,
 ('figure', 'out', 'whats'): 0.45454545454545453,
 ('out', 'whats', 'wrong'): 0.46153846153846156,
 ('whats', 'wrong', '</s>'): 0.42105263157894735,
 ('wrong', '</s>', '<s>'): 1.0,
 ('<s>', 'youre', 'the'): 0.04186046511627907,
 ('youre', 'the', 'oncologist'): 0.05555555555555555,
 ('the', 'oncologist', 'im'): 0.5,
 ('oncologist', 'im', 'just'): 1.0,
 ('im', 'just', 'a'): 0.09090909090909091,
 ('just', 'a', 'lowly'): 0.030303030303030304,
 ('a', 'lowly', 'infectious'): 1.0,
 ('lowly', 'infectious', 'disease'): 1.0,
 ('infectious', 'disease', 'guy'): 0.5,
 ('disease', 'guy', '</s>'): 1.0,
 ('guy', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'hah'): 0.000363460140537921,
 ('<s>', 'hah', 'yes'): 0.16666666666666666,
 ('hah', 'yes', 'just'): 1.0,
 ('yes', 'just', 'a'): 1.0,
 ('just', 'a', 'simple'): 0.030303030303030304,
 ('a', 'simple', 'country'): 0.14285714285714285,
 ('simple', 'country', 'doctor'): 1.0,
 ('country', 'doctor', '</s>'): 1.0,
 ('<s>', 'brain', 'tumors'): 0.2,
 ('brain', 'tumors', 'at'): 1.0,
 ('tumors', 'at', 'her'): 1.0,
 ('at', 'her', 'age'): 0.16666666666666666,
 ('her', 'age', 'are'): 0.3333333333333333,
 ('age', 'are', 'highly'): 1.0,
 ('are', 'highly', 'unlikely'): 1.0,
 ('highly', 'unlikely', '</s>'): 0.75,
 ('unlikely', '</s>', '<s>'): 1.0,
 ('<s>', 'shes', '29'): 0.007194244604316547,
 ('shes', '29', 'whatever'): 1.0,
 ('29', 'whatever', 'shes'): 1.0,
 ('whatever', 'shes', 'got'): 1.0,
 ('shes', 'got', 'is'): 0.07142857142857142,
 ('got', 'is', 'highly'): 1.0,
 ('is', 'highly', 'unlikely'): 0.5,
 ('</s>', '<s>', 'protein'): 6.05766900896535e-05,
 ('<s>', 'protein', 'markers'): 1.0,
 ('protein', 'markers', 'for'): 0.5,
 ('markers', 'for', 'the'): 1.0,
 ('for', 'the', 'three'): 0.008,
 ('the', 'three', 'most'): 0.16666666666666666,
 ('three', 'most', 'prevalent'): 1.0,
 ('most', 'prevalent', 'brain'): 1.0,
 ('prevalent', 'brain', 'cancers'): 1.0,
 ('brain', 'cancers', 'came'): 1.0,
 ('cancers', 'came', 'up'): 1.0,
 ('came', 'up', 'negative'): 0.3333333333333333,
 ('up', 'negative', '</s>'): 1.0,
 ('negative', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'thats'): 0.01296341167918585,
 ('<s>', 'thats', 'an'): 0.014018691588785047,
 ('thats', 'an', 'hmo'): 0.25,
 ('an', 'hmo', 'lab'): 0.5,
 ('hmo', 'lab', 'you'): 1.0,
 ('lab', 'you', 'might'): 1.0,
 ('you', 'might', 'as'): 0.1875,
 ('might', 'as', 'well'): 1.0,
 ('as', 'well', 'have'): 0.05263157894736842,
 ('well', 'have', 'sent'): 0.3333333333333333,
 ('have', 'sent', 'it'): 0.3333333333333333,
 ('sent', 'it', 'to'): 1.0,
 ('it', 'to', 'a'): 0.05128205128205128,
 ('to', 'a', 'high'): 0.025,
 ('a', 'high', 'school'): 0.6,
 ('high', 'school', 'kid'): 0.08333333333333333,
 ('school', 'kid', 'with'): 1.0,
 ('kid', 'with', 'a'): 1.0,
 ('with', 'a', 'chemistry'): 0.017857142857142856,
 ('a', 'chemistry', 'set'): 1.0,
 ('chemistry', 'set', '</s>'): 1.0,
 ('set', '</s>', '<s>'): 1.0,
 ('<s>', 'no', 'family'): 0.0041928721174004195,
 ('no', 'family', 'history'): 1.0,
 ('family', 'history', '</s>'): 0.46153846153846156,
 ('history', '</s>', '<s>'): 1.0,
 ('<s>', 'i', 'thought'): 0.0253592561284869,
 ('i', 'thought', 'your'): 0.022222222222222223,
 ('thought', 'your', 'uncle'): 1.0,
 ('your', 'uncle', 'died'): 1.0,
 ('uncle', 'died', 'of'): 1.0,
 ('died', 'of', 'cancer'): 0.5,
 ('of', 'cancer', '</s>'): 0.5714285714285714,
 ('cancer', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'other'): 0.000242306760358614,
 ('<s>', 'other', 'side'): 0.25,
 ('other', 'side', '</s>'): 1.0,
 ('side', '</s>', '<s>'): 1.0,
 ('<s>', 'no', 'environmental'): 0.0020964360587002098,
 ('no', 'environmental', 'factors'): 1.0,
 ('environmental', 'factors', '</s>'): 1.0,
 ('factors', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'that'): 0.006118245699055004,
 ('<s>', 'that', 'you'): 0.039603960396039604,
 ('that', 'you', 'know'): 0.03225806451612903,
 ('you', 'know', 'of'): 0.006535947712418301,
 ('know', 'of', '</s>'): 1.0,
 ('of', '</s>', '<s>'): 1.0,
 ('<s>', 'and', 'shes'): 0.0030864197530864196,
 ('and', 'shes', 'not'): 0.2857142857142857,
 ('shes', 'not', 'responding'): 0.09375,
 ('not', 'responding', 'to'): 0.7857142857142857,
 ('responding', 'to', 'radiation'): 0.07692307692307693,
 ('to', 'radiation', 'treatment'): 0.5,
 ('radiation', 'treatment', '</s>'): 1.0,
 ('treatment', '</s>', '<s>'): 1.0,
 ('</s>', '<s>', 'none'): 0.0006663435909861885,
 ('<s>', 'none', 'of'): 0.5454545454545454,
 ('none', 'of', 'which'): 0.07692307692307693,

In [25]:
# Example trigram probability
sample_trigram = ('why', 'are', 'you')
if sample_trigram in trigram_prob:
    print(f"P({sample_trigram[2]} | {sample_trigram[0]} {sample_trigram[1]}) = {trigram_prob[sample_trigram]}")

P(you | why are) = 0.8666666666666667

In [26]:
sample_trigram = ('a', 'chance', 'that')
if sample_trigram in trigram_prob:
    print(f"P({sample_trigram[2]} | {sample_trigram[0]} {sample_trigram[1]}) = {trigram_prob[sample_trigram]}")

P(that | a chance) = 0.08333333333333333

In [27]:
sample_trigram = ('have', 'you', 'seen')
if sample_trigram in trigram_prob:
    print(f"P({sample_trigram[2]} | {sample_trigram[0]} {sample_trigram[1]}) = {trigram_prob[sample_trigram]}")

P(seen | have you) = 0.03125

# Results/Analysis

In [28]:
# Raw vocab (baseline)
# Simple whitespace tokenization from raw "line"
raw_tokens = []
for text in df["line"].astype(str):
    raw_tokens.extend(text.split())

raw_vocab = set(raw_tokens)
raw_vocab_size = len(raw_vocab)

# Final vocab (after preprocessing)
final_vocab = set(corpus)
final_vocab_size = len(final_vocab)

# Reduction percentage
vocab_reduction_pct = ((raw_vocab_size - final_vocab_size) / raw_vocab_size) * 100 if raw_vocab_size else 0

# Sparsity / data-limitation stats
total_tokens = len(corpus)

unique_unigrams = len(unigram_counts)
unique_bigrams = len(bigram_counts)
unique_trigrams = len(trigram_counts)

hapax_unigrams = sum(1 for _, c in unigram_counts.items() if c == 1)
hapax_bigrams = sum(1 for _, c in bigram_counts.items() if c == 1)
hapax_trigrams = sum(1 for _, c in trigram_counts.items() if c == 1)

print("Raw vocab size:", raw_vocab_size)
print("Final vocab size:", final_vocab_size)
print(f"Vocab reduction: {vocab_reduction_pct:.2f}%")

print("Total tokens (final):", total_tokens)
print("Unique unigrams:", unique_unigrams)
print("Unique bigrams:", unique_bigrams)
print("Unique trigrams:", unique_trigrams)

print("Hapax unigrams (count=1):", hapax_unigrams)
print("Hapax bigrams (count=1):", hapax_bigrams)
print("Hapax trigrams (count=1):", hapax_trigrams)

Raw vocab size: 15683
Final vocab size: 8461
Vocab reduction: 46.05%
Total tokens (final): 140795
Unique unigrams: 8461
Unique bigrams: 49911
Unique trigrams: 88375
Hapax unigrams (count=1): 4086
Hapax bigrams (count=1): 36712
Hapax trigrams (count=1): 76070